// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/framework/user_op_conf.proto

package org.oneflow.core.framework;

public interface UserOpConfOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.UserOpConf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string op_type_name = 1;</code>
   */
  boolean hasOpTypeName();
  /**
   * <code>required string op_type_name = 1;</code>
   */
  java.lang.String getOpTypeName();
  /**
   * <code>required string op_type_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getOpTypeNameBytes();

  /**
   * <code>map&lt;string, .oneflow.UserOpConf.ListString&gt; input = 2;</code>
   */
  int getInputCount();
  /**
   * <code>map&lt;string, .oneflow.UserOpConf.ListString&gt; input = 2;</code>
   */
  boolean containsInput(
      java.lang.String key);
  /**
   * Use {@link #getInputMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.oneflow.core.framework.UserOpConf.ListString>
  getInput();
  /**
   * <code>map&lt;string, .oneflow.UserOpConf.ListString&gt; input = 2;</code>
   */
  java.util.Map<java.lang.String, org.oneflow.core.framework.UserOpConf.ListString>
  getInputMap();
  /**
   * <code>map&lt;string, .oneflow.UserOpConf.ListString&gt; input = 2;</code>
   */

  org.oneflow.core.framework.UserOpConf.ListString getInputOrDefault(
      java.lang.String key,
      org.oneflow.core.framework.UserOpConf.ListString defaultValue);
  /**
   * <code>map&lt;string, .oneflow.UserOpConf.ListString&gt; input = 2;</code>
   */

  org.oneflow.core.framework.UserOpConf.ListString getInputOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, .oneflow.UserOpConf.ListString&gt; output = 3;</code>
   */
  int getOutputCount();
  /**
   * <code>map&lt;string, .oneflow.UserOpConf.ListString&gt; output = 3;</code>
   */
  boolean containsOutput(
      java.lang.String key);
  /**
   * Use {@link #getOutputMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.oneflow.core.framework.UserOpConf.ListString>
  getOutput();
  /**
   * <code>map&lt;string, .oneflow.UserOpConf.ListString&gt; output = 3;</code>
   */
  java.util.Map<java.lang.String, org.oneflow.core.framework.UserOpConf.ListString>
  getOutputMap();
  /**
   * <code>map&lt;string, .oneflow.UserOpConf.ListString&gt; output = 3;</code>
   */

  org.oneflow.core.framework.UserOpConf.ListString getOutputOrDefault(
      java.lang.String key,
      org.oneflow.core.framework.UserOpConf.ListString defaultValue);
  /**
   * <code>map&lt;string, .oneflow.UserOpConf.ListString&gt; output = 3;</code>
   */

  org.oneflow.core.framework.UserOpConf.ListString getOutputOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, .oneflow.AttrValue&gt; attr = 4;</code>
   */
  int getAttrCount();
  /**
   * <code>map&lt;string, .oneflow.AttrValue&gt; attr = 4;</code>
   */
  boolean containsAttr(
      java.lang.String key);
  /**
   * Use {@link #getAttrMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, org.oneflow.core.framework.AttrValue>
  getAttr();
  /**
   * <code>map&lt;string, .oneflow.AttrValue&gt; attr = 4;</code>
   */
  java.util.Map<java.lang.String, org.oneflow.core.framework.AttrValue>
  getAttrMap();
  /**
   * <code>map&lt;string, .oneflow.AttrValue&gt; attr = 4;</code>
   */

  org.oneflow.core.framework.AttrValue getAttrOrDefault(
      java.lang.String key,
      org.oneflow.core.framework.AttrValue defaultValue);
  /**
   * <code>map&lt;string, .oneflow.AttrValue&gt; attr = 4;</code>
   */

  org.oneflow.core.framework.AttrValue getAttrOrThrow(
      java.lang.String key);
}
