// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/register/register_desc.proto

package org.oneflow.core.register;

public interface LbiBlobDescPairOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.LbiBlobDescPair)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .oneflow.LogicalBlobId lbi = 1;</code>
   */
  boolean hasLbi();
  /**
   * <code>required .oneflow.LogicalBlobId lbi = 1;</code>
   */
  org.oneflow.core.register.LogicalBlobId getLbi();
  /**
   * <code>required .oneflow.LogicalBlobId lbi = 1;</code>
   */
  org.oneflow.core.register.LogicalBlobIdOrBuilder getLbiOrBuilder();

  /**
   * <code>required .oneflow.BlobDescProto blob_desc = 2;</code>
   */
  boolean hasBlobDesc();
  /**
   * <code>required .oneflow.BlobDescProto blob_desc = 2;</code>
   */
  org.oneflow.core.register.BlobDescProto getBlobDesc();
  /**
   * <code>required .oneflow.BlobDescProto blob_desc = 2;</code>
   */
  org.oneflow.core.register.BlobDescProtoOrBuilder getBlobDescOrBuilder();
}
