// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/register/register_desc.proto

package org.oneflow.core.register;

public interface RegstDescTypeProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.RegstDescTypeProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .oneflow.DataRegstDesc data_regst_desc = 1;</code>
   */
  boolean hasDataRegstDesc();
  /**
   * <code>optional .oneflow.DataRegstDesc data_regst_desc = 1;</code>
   */
  org.oneflow.core.register.DataRegstDesc getDataRegstDesc();
  /**
   * <code>optional .oneflow.DataRegstDesc data_regst_desc = 1;</code>
   */
  org.oneflow.core.register.DataRegstDescOrBuilder getDataRegstDescOrBuilder();

  /**
   * <code>optional .oneflow.CtrlRegstDesc ctrl_regst_desc = 3;</code>
   */
  boolean hasCtrlRegstDesc();
  /**
   * <code>optional .oneflow.CtrlRegstDesc ctrl_regst_desc = 3;</code>
   */
  org.oneflow.core.register.CtrlRegstDesc getCtrlRegstDesc();
  /**
   * <code>optional .oneflow.CtrlRegstDesc ctrl_regst_desc = 3;</code>
   */
  org.oneflow.core.register.CtrlRegstDescOrBuilder getCtrlRegstDescOrBuilder();

  public org.oneflow.core.register.RegstDescTypeProto.TypeCase getTypeCase();
}
