// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/common/error.proto

package org.oneflow.core.common;

public interface ConfigResourceUnavailableErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.ConfigResourceUnavailableError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .oneflow.FieldValue field_value = 1;</code>
   */
  boolean hasFieldValue();
  /**
   * <code>required .oneflow.FieldValue field_value = 1;</code>
   */
  org.oneflow.core.common.FieldValue getFieldValue();
  /**
   * <code>required .oneflow.FieldValue field_value = 1;</code>
   */
  org.oneflow.core.common.FieldValueOrBuilder getFieldValueOrBuilder();
}
