// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/common/error.proto

package org.oneflow.core.common;

public interface LogicalBlobNameExistErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.LogicalBlobNameExistError)
    com.google.protobuf.MessageOrBuilder {
}
