// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/common/error.proto

package org.oneflow.core.common;

public interface MultipleOpKernelsMatchedErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.MultipleOpKernelsMatchedError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string matched_op_kernels_debug_str = 1;</code>
   */
  java.util.List<java.lang.String>
      getMatchedOpKernelsDebugStrList();
  /**
   * <code>repeated string matched_op_kernels_debug_str = 1;</code>
   */
  int getMatchedOpKernelsDebugStrCount();
  /**
   * <code>repeated string matched_op_kernels_debug_str = 1;</code>
   */
  java.lang.String getMatchedOpKernelsDebugStr(int index);
  /**
   * <code>repeated string matched_op_kernels_debug_str = 1;</code>
   */
  com.google.protobuf.ByteString
      getMatchedOpKernelsDebugStrBytes(int index);
}
