// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/common/error.proto

package org.oneflow.core.common;

/**
 * Protobuf type {@code oneflow.OpKernelNotFoundError}
 */
public  final class OpKernelNotFoundError extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:oneflow.OpKernelNotFoundError)
    OpKernelNotFoundErrorOrBuilder {
  // Use OpKernelNotFoundError.newBuilder() to construct.
  private OpKernelNotFoundError(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OpKernelNotFoundError() {
    opKernelsNotFoundDebugStr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OpKernelNotFoundError(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              opKernelsNotFoundDebugStr_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            opKernelsNotFoundDebugStr_.add(bs);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        opKernelsNotFoundDebugStr_ = opKernelsNotFoundDebugStr_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.oneflow.core.common.Error.internal_static_oneflow_OpKernelNotFoundError_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.oneflow.core.common.Error.internal_static_oneflow_OpKernelNotFoundError_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.oneflow.core.common.OpKernelNotFoundError.class, org.oneflow.core.common.OpKernelNotFoundError.Builder.class);
  }

  public static final int OP_KERNELS_NOT_FOUND_DEBUG_STR_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList opKernelsNotFoundDebugStr_;
  /**
   * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getOpKernelsNotFoundDebugStrList() {
    return opKernelsNotFoundDebugStr_;
  }
  /**
   * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
   */
  public int getOpKernelsNotFoundDebugStrCount() {
    return opKernelsNotFoundDebugStr_.size();
  }
  /**
   * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
   */
  public java.lang.String getOpKernelsNotFoundDebugStr(int index) {
    return opKernelsNotFoundDebugStr_.get(index);
  }
  /**
   * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
   */
  public com.google.protobuf.ByteString
      getOpKernelsNotFoundDebugStrBytes(int index) {
    return opKernelsNotFoundDebugStr_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < opKernelsNotFoundDebugStr_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, opKernelsNotFoundDebugStr_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < opKernelsNotFoundDebugStr_.size(); i++) {
        dataSize += computeStringSizeNoTag(opKernelsNotFoundDebugStr_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOpKernelsNotFoundDebugStrList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.oneflow.core.common.OpKernelNotFoundError)) {
      return super.equals(obj);
    }
    org.oneflow.core.common.OpKernelNotFoundError other = (org.oneflow.core.common.OpKernelNotFoundError) obj;

    boolean result = true;
    result = result && getOpKernelsNotFoundDebugStrList()
        .equals(other.getOpKernelsNotFoundDebugStrList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getOpKernelsNotFoundDebugStrCount() > 0) {
      hash = (37 * hash) + OP_KERNELS_NOT_FOUND_DEBUG_STR_FIELD_NUMBER;
      hash = (53 * hash) + getOpKernelsNotFoundDebugStrList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.oneflow.core.common.OpKernelNotFoundError parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.common.OpKernelNotFoundError parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.common.OpKernelNotFoundError parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.common.OpKernelNotFoundError parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.common.OpKernelNotFoundError parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.common.OpKernelNotFoundError parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.common.OpKernelNotFoundError parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.oneflow.core.common.OpKernelNotFoundError parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.common.OpKernelNotFoundError parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.common.OpKernelNotFoundError parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.oneflow.core.common.OpKernelNotFoundError prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code oneflow.OpKernelNotFoundError}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:oneflow.OpKernelNotFoundError)
      org.oneflow.core.common.OpKernelNotFoundErrorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.oneflow.core.common.Error.internal_static_oneflow_OpKernelNotFoundError_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.oneflow.core.common.Error.internal_static_oneflow_OpKernelNotFoundError_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.oneflow.core.common.OpKernelNotFoundError.class, org.oneflow.core.common.OpKernelNotFoundError.Builder.class);
    }

    // Construct using org.oneflow.core.common.OpKernelNotFoundError.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      opKernelsNotFoundDebugStr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.oneflow.core.common.Error.internal_static_oneflow_OpKernelNotFoundError_descriptor;
    }

    public org.oneflow.core.common.OpKernelNotFoundError getDefaultInstanceForType() {
      return org.oneflow.core.common.OpKernelNotFoundError.getDefaultInstance();
    }

    public org.oneflow.core.common.OpKernelNotFoundError build() {
      org.oneflow.core.common.OpKernelNotFoundError result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.oneflow.core.common.OpKernelNotFoundError buildPartial() {
      org.oneflow.core.common.OpKernelNotFoundError result = new org.oneflow.core.common.OpKernelNotFoundError(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        opKernelsNotFoundDebugStr_ = opKernelsNotFoundDebugStr_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.opKernelsNotFoundDebugStr_ = opKernelsNotFoundDebugStr_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.oneflow.core.common.OpKernelNotFoundError) {
        return mergeFrom((org.oneflow.core.common.OpKernelNotFoundError)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.oneflow.core.common.OpKernelNotFoundError other) {
      if (other == org.oneflow.core.common.OpKernelNotFoundError.getDefaultInstance()) return this;
      if (!other.opKernelsNotFoundDebugStr_.isEmpty()) {
        if (opKernelsNotFoundDebugStr_.isEmpty()) {
          opKernelsNotFoundDebugStr_ = other.opKernelsNotFoundDebugStr_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureOpKernelsNotFoundDebugStrIsMutable();
          opKernelsNotFoundDebugStr_.addAll(other.opKernelsNotFoundDebugStr_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.oneflow.core.common.OpKernelNotFoundError parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.oneflow.core.common.OpKernelNotFoundError) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList opKernelsNotFoundDebugStr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureOpKernelsNotFoundDebugStrIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        opKernelsNotFoundDebugStr_ = new com.google.protobuf.LazyStringArrayList(opKernelsNotFoundDebugStr_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getOpKernelsNotFoundDebugStrList() {
      return opKernelsNotFoundDebugStr_.getUnmodifiableView();
    }
    /**
     * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
     */
    public int getOpKernelsNotFoundDebugStrCount() {
      return opKernelsNotFoundDebugStr_.size();
    }
    /**
     * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
     */
    public java.lang.String getOpKernelsNotFoundDebugStr(int index) {
      return opKernelsNotFoundDebugStr_.get(index);
    }
    /**
     * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOpKernelsNotFoundDebugStrBytes(int index) {
      return opKernelsNotFoundDebugStr_.getByteString(index);
    }
    /**
     * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
     */
    public Builder setOpKernelsNotFoundDebugStr(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOpKernelsNotFoundDebugStrIsMutable();
      opKernelsNotFoundDebugStr_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
     */
    public Builder addOpKernelsNotFoundDebugStr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOpKernelsNotFoundDebugStrIsMutable();
      opKernelsNotFoundDebugStr_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
     */
    public Builder addAllOpKernelsNotFoundDebugStr(
        java.lang.Iterable<java.lang.String> values) {
      ensureOpKernelsNotFoundDebugStrIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, opKernelsNotFoundDebugStr_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
     */
    public Builder clearOpKernelsNotFoundDebugStr() {
      opKernelsNotFoundDebugStr_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
     */
    public Builder addOpKernelsNotFoundDebugStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOpKernelsNotFoundDebugStrIsMutable();
      opKernelsNotFoundDebugStr_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:oneflow.OpKernelNotFoundError)
  }

  // @@protoc_insertion_point(class_scope:oneflow.OpKernelNotFoundError)
  private static final org.oneflow.core.common.OpKernelNotFoundError DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.oneflow.core.common.OpKernelNotFoundError();
  }

  public static org.oneflow.core.common.OpKernelNotFoundError getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<OpKernelNotFoundError>
      PARSER = new com.google.protobuf.AbstractParser<OpKernelNotFoundError>() {
    public OpKernelNotFoundError parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new OpKernelNotFoundError(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OpKernelNotFoundError> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OpKernelNotFoundError> getParserForType() {
    return PARSER;
  }

  public org.oneflow.core.common.OpKernelNotFoundError getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

