// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/common/error.proto

package org.oneflow.core.common;

public interface OpKernelNotFoundErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.OpKernelNotFoundError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
   */
  java.util.List<java.lang.String>
      getOpKernelsNotFoundDebugStrList();
  /**
   * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
   */
  int getOpKernelsNotFoundDebugStrCount();
  /**
   * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
   */
  java.lang.String getOpKernelsNotFoundDebugStr(int index);
  /**
   * <code>repeated string op_kernels_not_found_debug_str = 1;</code>
   */
  com.google.protobuf.ByteString
      getOpKernelsNotFoundDebugStrBytes(int index);
}
