// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/common/error.proto

package org.oneflow.core.common;

public interface SymbolIdUninitializedErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.SymbolIdUninitializedError)
    com.google.protobuf.MessageOrBuilder {
}
