// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/actor/act_event.proto

package org.oneflow.core.actor;

/**
 * Protobuf type {@code oneflow.ReadableRegstInfo}
 */
public  final class ReadableRegstInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:oneflow.ReadableRegstInfo)
    ReadableRegstInfoOrBuilder {
  // Use ReadableRegstInfo.newBuilder() to construct.
  private ReadableRegstInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReadableRegstInfo() {
    regstDescId_ = 0L;
    actId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReadableRegstInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            regstDescId_ = input.readInt64();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            actId_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.oneflow.core.actor.ActEventOuterClass.internal_static_oneflow_ReadableRegstInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.oneflow.core.actor.ActEventOuterClass.internal_static_oneflow_ReadableRegstInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.oneflow.core.actor.ReadableRegstInfo.class, org.oneflow.core.actor.ReadableRegstInfo.Builder.class);
  }

  private int bitField0_;
  public static final int REGST_DESC_ID_FIELD_NUMBER = 1;
  private long regstDescId_;
  /**
   * <code>required int64 regst_desc_id = 1;</code>
   */
  public boolean hasRegstDescId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int64 regst_desc_id = 1;</code>
   */
  public long getRegstDescId() {
    return regstDescId_;
  }

  public static final int ACT_ID_FIELD_NUMBER = 2;
  private long actId_;
  /**
   * <code>required int64 act_id = 2;</code>
   */
  public boolean hasActId() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int64 act_id = 2;</code>
   */
  public long getActId() {
    return actId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasRegstDescId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasActId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, regstDescId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt64(2, actId_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, regstDescId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, actId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.oneflow.core.actor.ReadableRegstInfo)) {
      return super.equals(obj);
    }
    org.oneflow.core.actor.ReadableRegstInfo other = (org.oneflow.core.actor.ReadableRegstInfo) obj;

    boolean result = true;
    result = result && (hasRegstDescId() == other.hasRegstDescId());
    if (hasRegstDescId()) {
      result = result && (getRegstDescId()
          == other.getRegstDescId());
    }
    result = result && (hasActId() == other.hasActId());
    if (hasActId()) {
      result = result && (getActId()
          == other.getActId());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasRegstDescId()) {
      hash = (37 * hash) + REGST_DESC_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRegstDescId());
    }
    if (hasActId()) {
      hash = (37 * hash) + ACT_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getActId());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.oneflow.core.actor.ReadableRegstInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.actor.ReadableRegstInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.actor.ReadableRegstInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.actor.ReadableRegstInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.actor.ReadableRegstInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.actor.ReadableRegstInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.actor.ReadableRegstInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.oneflow.core.actor.ReadableRegstInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.actor.ReadableRegstInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.actor.ReadableRegstInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.oneflow.core.actor.ReadableRegstInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code oneflow.ReadableRegstInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:oneflow.ReadableRegstInfo)
      org.oneflow.core.actor.ReadableRegstInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.oneflow.core.actor.ActEventOuterClass.internal_static_oneflow_ReadableRegstInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.oneflow.core.actor.ActEventOuterClass.internal_static_oneflow_ReadableRegstInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.oneflow.core.actor.ReadableRegstInfo.class, org.oneflow.core.actor.ReadableRegstInfo.Builder.class);
    }

    // Construct using org.oneflow.core.actor.ReadableRegstInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      regstDescId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      actId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.oneflow.core.actor.ActEventOuterClass.internal_static_oneflow_ReadableRegstInfo_descriptor;
    }

    public org.oneflow.core.actor.ReadableRegstInfo getDefaultInstanceForType() {
      return org.oneflow.core.actor.ReadableRegstInfo.getDefaultInstance();
    }

    public org.oneflow.core.actor.ReadableRegstInfo build() {
      org.oneflow.core.actor.ReadableRegstInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.oneflow.core.actor.ReadableRegstInfo buildPartial() {
      org.oneflow.core.actor.ReadableRegstInfo result = new org.oneflow.core.actor.ReadableRegstInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.regstDescId_ = regstDescId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.actId_ = actId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.oneflow.core.actor.ReadableRegstInfo) {
        return mergeFrom((org.oneflow.core.actor.ReadableRegstInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.oneflow.core.actor.ReadableRegstInfo other) {
      if (other == org.oneflow.core.actor.ReadableRegstInfo.getDefaultInstance()) return this;
      if (other.hasRegstDescId()) {
        setRegstDescId(other.getRegstDescId());
      }
      if (other.hasActId()) {
        setActId(other.getActId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasRegstDescId()) {
        return false;
      }
      if (!hasActId()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.oneflow.core.actor.ReadableRegstInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.oneflow.core.actor.ReadableRegstInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long regstDescId_ ;
    /**
     * <code>required int64 regst_desc_id = 1;</code>
     */
    public boolean hasRegstDescId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 regst_desc_id = 1;</code>
     */
    public long getRegstDescId() {
      return regstDescId_;
    }
    /**
     * <code>required int64 regst_desc_id = 1;</code>
     */
    public Builder setRegstDescId(long value) {
      bitField0_ |= 0x00000001;
      regstDescId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 regst_desc_id = 1;</code>
     */
    public Builder clearRegstDescId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      regstDescId_ = 0L;
      onChanged();
      return this;
    }

    private long actId_ ;
    /**
     * <code>required int64 act_id = 2;</code>
     */
    public boolean hasActId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 act_id = 2;</code>
     */
    public long getActId() {
      return actId_;
    }
    /**
     * <code>required int64 act_id = 2;</code>
     */
    public Builder setActId(long value) {
      bitField0_ |= 0x00000002;
      actId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 act_id = 2;</code>
     */
    public Builder clearActId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      actId_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:oneflow.ReadableRegstInfo)
  }

  // @@protoc_insertion_point(class_scope:oneflow.ReadableRegstInfo)
  private static final org.oneflow.core.actor.ReadableRegstInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.oneflow.core.actor.ReadableRegstInfo();
  }

  public static org.oneflow.core.actor.ReadableRegstInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ReadableRegstInfo>
      PARSER = new com.google.protobuf.AbstractParser<ReadableRegstInfo>() {
    public ReadableRegstInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReadableRegstInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReadableRegstInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReadableRegstInfo> getParserForType() {
    return PARSER;
  }

  public org.oneflow.core.actor.ReadableRegstInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

