// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/operator/op_conf.proto

package org.oneflow.core.operator;

public interface CaseOpConfOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.CaseOpConf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string in = 1;</code>
   */
  boolean hasIn();
  /**
   * <code>required string in = 1;</code>
   */
  java.lang.String getIn();
  /**
   * <code>required string in = 1;</code>
   */
  com.google.protobuf.ByteString
      getInBytes();

  /**
   * <code>repeated string out = 2;</code>
   */
  java.util.List<java.lang.String>
      getOutList();
  /**
   * <code>repeated string out = 2;</code>
   */
  int getOutCount();
  /**
   * <code>repeated string out = 2;</code>
   */
  java.lang.String getOut(int index);
  /**
   * <code>repeated string out = 2;</code>
   */
  com.google.protobuf.ByteString
      getOutBytes(int index);
}
