// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/operator/op_conf.proto

package org.oneflow.core.operator;

/**
 * Protobuf type {@code oneflow.DistributeConcatOpConf}
 */
public  final class DistributeConcatOpConf extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:oneflow.DistributeConcatOpConf)
    DistributeConcatOpConfOrBuilder {
  // Use DistributeConcatOpConf.newBuilder() to construct.
  private DistributeConcatOpConf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DistributeConcatOpConf() {
    in_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    out_ = "";
    axis_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DistributeConcatOpConf(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              in_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            in_.add(bs);
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            out_ = bs;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000002;
            axis_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        in_ = in_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.oneflow.core.operator.OpConf.internal_static_oneflow_DistributeConcatOpConf_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.oneflow.core.operator.OpConf.internal_static_oneflow_DistributeConcatOpConf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.oneflow.core.operator.DistributeConcatOpConf.class, org.oneflow.core.operator.DistributeConcatOpConf.Builder.class);
  }

  private int bitField0_;
  public static final int IN_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList in_;
  /**
   * <code>repeated string in = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getInList() {
    return in_;
  }
  /**
   * <code>repeated string in = 1;</code>
   */
  public int getInCount() {
    return in_.size();
  }
  /**
   * <code>repeated string in = 1;</code>
   */
  public java.lang.String getIn(int index) {
    return in_.get(index);
  }
  /**
   * <code>repeated string in = 1;</code>
   */
  public com.google.protobuf.ByteString
      getInBytes(int index) {
    return in_.getByteString(index);
  }

  public static final int OUT_FIELD_NUMBER = 2;
  private volatile java.lang.Object out_;
  /**
   * <code>required string out = 2;</code>
   */
  public boolean hasOut() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string out = 2;</code>
   */
  public java.lang.String getOut() {
    java.lang.Object ref = out_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        out_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string out = 2;</code>
   */
  public com.google.protobuf.ByteString
      getOutBytes() {
    java.lang.Object ref = out_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      out_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AXIS_FIELD_NUMBER = 3;
  private int axis_;
  /**
   * <code>required int32 axis = 3;</code>
   */
  public boolean hasAxis() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int32 axis = 3;</code>
   */
  public int getAxis() {
    return axis_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasOut()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasAxis()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < in_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, in_.getRaw(i));
    }
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, out_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(3, axis_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < in_.size(); i++) {
        dataSize += computeStringSizeNoTag(in_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getInList().size();
    }
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, out_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, axis_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.oneflow.core.operator.DistributeConcatOpConf)) {
      return super.equals(obj);
    }
    org.oneflow.core.operator.DistributeConcatOpConf other = (org.oneflow.core.operator.DistributeConcatOpConf) obj;

    boolean result = true;
    result = result && getInList()
        .equals(other.getInList());
    result = result && (hasOut() == other.hasOut());
    if (hasOut()) {
      result = result && getOut()
          .equals(other.getOut());
    }
    result = result && (hasAxis() == other.hasAxis());
    if (hasAxis()) {
      result = result && (getAxis()
          == other.getAxis());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getInCount() > 0) {
      hash = (37 * hash) + IN_FIELD_NUMBER;
      hash = (53 * hash) + getInList().hashCode();
    }
    if (hasOut()) {
      hash = (37 * hash) + OUT_FIELD_NUMBER;
      hash = (53 * hash) + getOut().hashCode();
    }
    if (hasAxis()) {
      hash = (37 * hash) + AXIS_FIELD_NUMBER;
      hash = (53 * hash) + getAxis();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.oneflow.core.operator.DistributeConcatOpConf parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.operator.DistributeConcatOpConf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.operator.DistributeConcatOpConf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.operator.DistributeConcatOpConf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.operator.DistributeConcatOpConf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.operator.DistributeConcatOpConf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.operator.DistributeConcatOpConf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.oneflow.core.operator.DistributeConcatOpConf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.operator.DistributeConcatOpConf parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.operator.DistributeConcatOpConf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.oneflow.core.operator.DistributeConcatOpConf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code oneflow.DistributeConcatOpConf}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:oneflow.DistributeConcatOpConf)
      org.oneflow.core.operator.DistributeConcatOpConfOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.oneflow.core.operator.OpConf.internal_static_oneflow_DistributeConcatOpConf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.oneflow.core.operator.OpConf.internal_static_oneflow_DistributeConcatOpConf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.oneflow.core.operator.DistributeConcatOpConf.class, org.oneflow.core.operator.DistributeConcatOpConf.Builder.class);
    }

    // Construct using org.oneflow.core.operator.DistributeConcatOpConf.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      in_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      out_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      axis_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.oneflow.core.operator.OpConf.internal_static_oneflow_DistributeConcatOpConf_descriptor;
    }

    public org.oneflow.core.operator.DistributeConcatOpConf getDefaultInstanceForType() {
      return org.oneflow.core.operator.DistributeConcatOpConf.getDefaultInstance();
    }

    public org.oneflow.core.operator.DistributeConcatOpConf build() {
      org.oneflow.core.operator.DistributeConcatOpConf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.oneflow.core.operator.DistributeConcatOpConf buildPartial() {
      org.oneflow.core.operator.DistributeConcatOpConf result = new org.oneflow.core.operator.DistributeConcatOpConf(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        in_ = in_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.in_ = in_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000001;
      }
      result.out_ = out_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000002;
      }
      result.axis_ = axis_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.oneflow.core.operator.DistributeConcatOpConf) {
        return mergeFrom((org.oneflow.core.operator.DistributeConcatOpConf)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.oneflow.core.operator.DistributeConcatOpConf other) {
      if (other == org.oneflow.core.operator.DistributeConcatOpConf.getDefaultInstance()) return this;
      if (!other.in_.isEmpty()) {
        if (in_.isEmpty()) {
          in_ = other.in_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureInIsMutable();
          in_.addAll(other.in_);
        }
        onChanged();
      }
      if (other.hasOut()) {
        bitField0_ |= 0x00000002;
        out_ = other.out_;
        onChanged();
      }
      if (other.hasAxis()) {
        setAxis(other.getAxis());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasOut()) {
        return false;
      }
      if (!hasAxis()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.oneflow.core.operator.DistributeConcatOpConf parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.oneflow.core.operator.DistributeConcatOpConf) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList in_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureInIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        in_ = new com.google.protobuf.LazyStringArrayList(in_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string in = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInList() {
      return in_.getUnmodifiableView();
    }
    /**
     * <code>repeated string in = 1;</code>
     */
    public int getInCount() {
      return in_.size();
    }
    /**
     * <code>repeated string in = 1;</code>
     */
    public java.lang.String getIn(int index) {
      return in_.get(index);
    }
    /**
     * <code>repeated string in = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInBytes(int index) {
      return in_.getByteString(index);
    }
    /**
     * <code>repeated string in = 1;</code>
     */
    public Builder setIn(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInIsMutable();
      in_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string in = 1;</code>
     */
    public Builder addIn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInIsMutable();
      in_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string in = 1;</code>
     */
    public Builder addAllIn(
        java.lang.Iterable<java.lang.String> values) {
      ensureInIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, in_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string in = 1;</code>
     */
    public Builder clearIn() {
      in_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string in = 1;</code>
     */
    public Builder addInBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInIsMutable();
      in_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object out_ = "";
    /**
     * <code>required string out = 2;</code>
     */
    public boolean hasOut() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string out = 2;</code>
     */
    public java.lang.String getOut() {
      java.lang.Object ref = out_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          out_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string out = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOutBytes() {
      java.lang.Object ref = out_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        out_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string out = 2;</code>
     */
    public Builder setOut(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      out_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string out = 2;</code>
     */
    public Builder clearOut() {
      bitField0_ = (bitField0_ & ~0x00000002);
      out_ = getDefaultInstance().getOut();
      onChanged();
      return this;
    }
    /**
     * <code>required string out = 2;</code>
     */
    public Builder setOutBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      out_ = value;
      onChanged();
      return this;
    }

    private int axis_ ;
    /**
     * <code>required int32 axis = 3;</code>
     */
    public boolean hasAxis() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 axis = 3;</code>
     */
    public int getAxis() {
      return axis_;
    }
    /**
     * <code>required int32 axis = 3;</code>
     */
    public Builder setAxis(int value) {
      bitField0_ |= 0x00000004;
      axis_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 axis = 3;</code>
     */
    public Builder clearAxis() {
      bitField0_ = (bitField0_ & ~0x00000004);
      axis_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:oneflow.DistributeConcatOpConf)
  }

  // @@protoc_insertion_point(class_scope:oneflow.DistributeConcatOpConf)
  private static final org.oneflow.core.operator.DistributeConcatOpConf DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.oneflow.core.operator.DistributeConcatOpConf();
  }

  public static org.oneflow.core.operator.DistributeConcatOpConf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<DistributeConcatOpConf>
      PARSER = new com.google.protobuf.AbstractParser<DistributeConcatOpConf>() {
    public DistributeConcatOpConf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DistributeConcatOpConf(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DistributeConcatOpConf> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DistributeConcatOpConf> getParserForType() {
    return PARSER;
  }

  public org.oneflow.core.operator.DistributeConcatOpConf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

