// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/operator/arg_modifier_signature.proto

package org.oneflow.core.operator;

public interface InputBlobModifierOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.InputBlobModifier)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool is_mutable = 1 [default = false];</code>
   */
  boolean hasIsMutable();
  /**
   * <code>optional bool is_mutable = 1 [default = false];</code>
   */
  boolean getIsMutable();

  /**
   * <code>optional bool requires_grad = 3 [default = false];</code>
   */
  boolean hasRequiresGrad();
  /**
   * <code>optional bool requires_grad = 3 [default = false];</code>
   */
  boolean getRequiresGrad();
}
