// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/operator/op_conf.proto

package org.oneflow.core.operator;

public interface ModelSaveOpConfOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.ModelSaveOpConf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string path = 1;</code>
   */
  boolean hasPath();
  /**
   * <code>required string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <code>required string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>repeated string in = 2;</code>
   */
  java.util.List<java.lang.String>
      getInList();
  /**
   * <code>repeated string in = 2;</code>
   */
  int getInCount();
  /**
   * <code>repeated string in = 2;</code>
   */
  java.lang.String getIn(int index);
  /**
   * <code>repeated string in = 2;</code>
   */
  com.google.protobuf.ByteString
      getInBytes(int index);

  /**
   * <code>repeated string key = 3;</code>
   */
  java.util.List<java.lang.String>
      getKeyList();
  /**
   * <code>repeated string key = 3;</code>
   */
  int getKeyCount();
  /**
   * <code>repeated string key = 3;</code>
   */
  java.lang.String getKey(int index);
  /**
   * <code>repeated string key = 3;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes(int index);
}
