// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/job/blob_lifetime_signature.proto

package org.oneflow.core.job;

public interface BlobLastUsedSignatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.BlobLastUsedSignature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, bool&gt; bn_in_op2blob_last_used = 1;</code>
   */
  int getBnInOp2BlobLastUsedCount();
  /**
   * <code>map&lt;string, bool&gt; bn_in_op2blob_last_used = 1;</code>
   */
  boolean containsBnInOp2BlobLastUsed(
      java.lang.String key);
  /**
   * Use {@link #getBnInOp2BlobLastUsedMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Boolean>
  getBnInOp2BlobLastUsed();
  /**
   * <code>map&lt;string, bool&gt; bn_in_op2blob_last_used = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.Boolean>
  getBnInOp2BlobLastUsedMap();
  /**
   * <code>map&lt;string, bool&gt; bn_in_op2blob_last_used = 1;</code>
   */

  boolean getBnInOp2BlobLastUsedOrDefault(
      java.lang.String key,
      boolean defaultValue);
  /**
   * <code>map&lt;string, bool&gt; bn_in_op2blob_last_used = 1;</code>
   */

  boolean getBnInOp2BlobLastUsedOrThrow(
      java.lang.String key);
}
