// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/job/distribute_hirarchy.proto

package org.oneflow.core.job;

/**
 * Protobuf type {@code oneflow.DistributeHirarchy}
 */
public  final class DistributeHirarchy extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:oneflow.DistributeHirarchy)
    DistributeHirarchyOrBuilder {
  // Use DistributeHirarchy.newBuilder() to construct.
  private DistributeHirarchy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DistributeHirarchy() {
    dim_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DistributeHirarchy(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              dim_ = new java.util.ArrayList<org.oneflow.core.job.DistributeDim>();
              mutable_bitField0_ |= 0x00000001;
            }
            dim_.add(
                input.readMessage(org.oneflow.core.job.DistributeDim.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        dim_ = java.util.Collections.unmodifiableList(dim_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.oneflow.core.job.DistributeHirarchyOuterClass.internal_static_oneflow_DistributeHirarchy_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.oneflow.core.job.DistributeHirarchyOuterClass.internal_static_oneflow_DistributeHirarchy_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.oneflow.core.job.DistributeHirarchy.class, org.oneflow.core.job.DistributeHirarchy.Builder.class);
  }

  public static final int DIM_FIELD_NUMBER = 1;
  private java.util.List<org.oneflow.core.job.DistributeDim> dim_;
  /**
   * <code>repeated .oneflow.DistributeDim dim = 1;</code>
   */
  public java.util.List<org.oneflow.core.job.DistributeDim> getDimList() {
    return dim_;
  }
  /**
   * <code>repeated .oneflow.DistributeDim dim = 1;</code>
   */
  public java.util.List<? extends org.oneflow.core.job.DistributeDimOrBuilder> 
      getDimOrBuilderList() {
    return dim_;
  }
  /**
   * <code>repeated .oneflow.DistributeDim dim = 1;</code>
   */
  public int getDimCount() {
    return dim_.size();
  }
  /**
   * <code>repeated .oneflow.DistributeDim dim = 1;</code>
   */
  public org.oneflow.core.job.DistributeDim getDim(int index) {
    return dim_.get(index);
  }
  /**
   * <code>repeated .oneflow.DistributeDim dim = 1;</code>
   */
  public org.oneflow.core.job.DistributeDimOrBuilder getDimOrBuilder(
      int index) {
    return dim_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getDimCount(); i++) {
      if (!getDim(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < dim_.size(); i++) {
      output.writeMessage(1, dim_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < dim_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, dim_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.oneflow.core.job.DistributeHirarchy)) {
      return super.equals(obj);
    }
    org.oneflow.core.job.DistributeHirarchy other = (org.oneflow.core.job.DistributeHirarchy) obj;

    boolean result = true;
    result = result && getDimList()
        .equals(other.getDimList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getDimCount() > 0) {
      hash = (37 * hash) + DIM_FIELD_NUMBER;
      hash = (53 * hash) + getDimList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.oneflow.core.job.DistributeHirarchy parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.job.DistributeHirarchy parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.job.DistributeHirarchy parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.job.DistributeHirarchy parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.job.DistributeHirarchy parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.DistributeHirarchy parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.job.DistributeHirarchy parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.DistributeHirarchy parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.job.DistributeHirarchy parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.DistributeHirarchy parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.oneflow.core.job.DistributeHirarchy prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code oneflow.DistributeHirarchy}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:oneflow.DistributeHirarchy)
      org.oneflow.core.job.DistributeHirarchyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.oneflow.core.job.DistributeHirarchyOuterClass.internal_static_oneflow_DistributeHirarchy_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.oneflow.core.job.DistributeHirarchyOuterClass.internal_static_oneflow_DistributeHirarchy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.oneflow.core.job.DistributeHirarchy.class, org.oneflow.core.job.DistributeHirarchy.Builder.class);
    }

    // Construct using org.oneflow.core.job.DistributeHirarchy.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDimFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (dimBuilder_ == null) {
        dim_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        dimBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.oneflow.core.job.DistributeHirarchyOuterClass.internal_static_oneflow_DistributeHirarchy_descriptor;
    }

    public org.oneflow.core.job.DistributeHirarchy getDefaultInstanceForType() {
      return org.oneflow.core.job.DistributeHirarchy.getDefaultInstance();
    }

    public org.oneflow.core.job.DistributeHirarchy build() {
      org.oneflow.core.job.DistributeHirarchy result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.oneflow.core.job.DistributeHirarchy buildPartial() {
      org.oneflow.core.job.DistributeHirarchy result = new org.oneflow.core.job.DistributeHirarchy(this);
      int from_bitField0_ = bitField0_;
      if (dimBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          dim_ = java.util.Collections.unmodifiableList(dim_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dim_ = dim_;
      } else {
        result.dim_ = dimBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.oneflow.core.job.DistributeHirarchy) {
        return mergeFrom((org.oneflow.core.job.DistributeHirarchy)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.oneflow.core.job.DistributeHirarchy other) {
      if (other == org.oneflow.core.job.DistributeHirarchy.getDefaultInstance()) return this;
      if (dimBuilder_ == null) {
        if (!other.dim_.isEmpty()) {
          if (dim_.isEmpty()) {
            dim_ = other.dim_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDimIsMutable();
            dim_.addAll(other.dim_);
          }
          onChanged();
        }
      } else {
        if (!other.dim_.isEmpty()) {
          if (dimBuilder_.isEmpty()) {
            dimBuilder_.dispose();
            dimBuilder_ = null;
            dim_ = other.dim_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dimBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDimFieldBuilder() : null;
          } else {
            dimBuilder_.addAllMessages(other.dim_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      for (int i = 0; i < getDimCount(); i++) {
        if (!getDim(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.oneflow.core.job.DistributeHirarchy parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.oneflow.core.job.DistributeHirarchy) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.oneflow.core.job.DistributeDim> dim_ =
      java.util.Collections.emptyList();
    private void ensureDimIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        dim_ = new java.util.ArrayList<org.oneflow.core.job.DistributeDim>(dim_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.oneflow.core.job.DistributeDim, org.oneflow.core.job.DistributeDim.Builder, org.oneflow.core.job.DistributeDimOrBuilder> dimBuilder_;

    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public java.util.List<org.oneflow.core.job.DistributeDim> getDimList() {
      if (dimBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dim_);
      } else {
        return dimBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public int getDimCount() {
      if (dimBuilder_ == null) {
        return dim_.size();
      } else {
        return dimBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public org.oneflow.core.job.DistributeDim getDim(int index) {
      if (dimBuilder_ == null) {
        return dim_.get(index);
      } else {
        return dimBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public Builder setDim(
        int index, org.oneflow.core.job.DistributeDim value) {
      if (dimBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDimIsMutable();
        dim_.set(index, value);
        onChanged();
      } else {
        dimBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public Builder setDim(
        int index, org.oneflow.core.job.DistributeDim.Builder builderForValue) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        dim_.set(index, builderForValue.build());
        onChanged();
      } else {
        dimBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public Builder addDim(org.oneflow.core.job.DistributeDim value) {
      if (dimBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDimIsMutable();
        dim_.add(value);
        onChanged();
      } else {
        dimBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public Builder addDim(
        int index, org.oneflow.core.job.DistributeDim value) {
      if (dimBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDimIsMutable();
        dim_.add(index, value);
        onChanged();
      } else {
        dimBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public Builder addDim(
        org.oneflow.core.job.DistributeDim.Builder builderForValue) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        dim_.add(builderForValue.build());
        onChanged();
      } else {
        dimBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public Builder addDim(
        int index, org.oneflow.core.job.DistributeDim.Builder builderForValue) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        dim_.add(index, builderForValue.build());
        onChanged();
      } else {
        dimBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public Builder addAllDim(
        java.lang.Iterable<? extends org.oneflow.core.job.DistributeDim> values) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dim_);
        onChanged();
      } else {
        dimBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public Builder clearDim() {
      if (dimBuilder_ == null) {
        dim_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dimBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public Builder removeDim(int index) {
      if (dimBuilder_ == null) {
        ensureDimIsMutable();
        dim_.remove(index);
        onChanged();
      } else {
        dimBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public org.oneflow.core.job.DistributeDim.Builder getDimBuilder(
        int index) {
      return getDimFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public org.oneflow.core.job.DistributeDimOrBuilder getDimOrBuilder(
        int index) {
      if (dimBuilder_ == null) {
        return dim_.get(index);  } else {
        return dimBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public java.util.List<? extends org.oneflow.core.job.DistributeDimOrBuilder> 
         getDimOrBuilderList() {
      if (dimBuilder_ != null) {
        return dimBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dim_);
      }
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public org.oneflow.core.job.DistributeDim.Builder addDimBuilder() {
      return getDimFieldBuilder().addBuilder(
          org.oneflow.core.job.DistributeDim.getDefaultInstance());
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public org.oneflow.core.job.DistributeDim.Builder addDimBuilder(
        int index) {
      return getDimFieldBuilder().addBuilder(
          index, org.oneflow.core.job.DistributeDim.getDefaultInstance());
    }
    /**
     * <code>repeated .oneflow.DistributeDim dim = 1;</code>
     */
    public java.util.List<org.oneflow.core.job.DistributeDim.Builder> 
         getDimBuilderList() {
      return getDimFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.oneflow.core.job.DistributeDim, org.oneflow.core.job.DistributeDim.Builder, org.oneflow.core.job.DistributeDimOrBuilder> 
        getDimFieldBuilder() {
      if (dimBuilder_ == null) {
        dimBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.oneflow.core.job.DistributeDim, org.oneflow.core.job.DistributeDim.Builder, org.oneflow.core.job.DistributeDimOrBuilder>(
                dim_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        dim_ = null;
      }
      return dimBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:oneflow.DistributeHirarchy)
  }

  // @@protoc_insertion_point(class_scope:oneflow.DistributeHirarchy)
  private static final org.oneflow.core.job.DistributeHirarchy DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.oneflow.core.job.DistributeHirarchy();
  }

  public static org.oneflow.core.job.DistributeHirarchy getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<DistributeHirarchy>
      PARSER = new com.google.protobuf.AbstractParser<DistributeHirarchy>() {
    public DistributeHirarchy parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DistributeHirarchy(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DistributeHirarchy> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DistributeHirarchy> getParserForType() {
    return PARSER;
  }

  public org.oneflow.core.job.DistributeHirarchy getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

