// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/job/env.proto

package org.oneflow.core.job;

public final class Env {
  private Env() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oneflow_Machine_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_oneflow_Machine_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oneflow_CppLoggingConf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_oneflow_CppLoggingConf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oneflow_EnvProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_oneflow_EnvProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032oneflow/core/job/env.proto\022\007oneflow\032)o" +
      "neflow/core/control/ctrl_bootstrap.proto" +
      "\"]\n\007Machine\022\n\n\002id\030\001 \002(\003\022\014\n\004addr\030\002 \002(\t\022\033\n" +
      "\017ctrl_port_agent\030\003 \001(\005:\002-1\022\033\n\017data_port_" +
      "agent\030\004 \001(\005:\002-1\"Y\n\016CppLoggingConf\022\026\n\007log" +
      "_dir\030\001 \001(\t:\005./log\022\026\n\013logtostderr\030\002 \001(\005:\001" +
      "0\022\027\n\013logbuflevel\030\003 \001(\005:\002-1\"\347\001\n\010EnvProto\022" +
      "!\n\007machine\030\001 \003(\0132\020.oneflow.Machine\022\021\n\tct" +
      "rl_port\030\002 \002(\005\022\025\n\tdata_port\030\003 \001(\005:\002-1\0221\n\020" +
      "cpp_logging_conf\030\004 \001(\0132\027.oneflow.CppLogg",
      "ingConf\0223\n\023ctrl_bootstrap_conf\030\005 \001(\0132\026.o" +
      "neflow.BootstrapConf\022&\n\027is_default_physi" +
      "cal_env\030\006 \001(\010:\005falseB\030\n\024org.oneflow.core" +
      ".jobP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          oneflow.CtrlBootstrap.getDescriptor(),
        }, assigner);
    internal_static_oneflow_Machine_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_oneflow_Machine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_oneflow_Machine_descriptor,
        new java.lang.String[] { "Id", "Addr", "CtrlPortAgent", "DataPortAgent", });
    internal_static_oneflow_CppLoggingConf_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_oneflow_CppLoggingConf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_oneflow_CppLoggingConf_descriptor,
        new java.lang.String[] { "LogDir", "Logtostderr", "Logbuflevel", });
    internal_static_oneflow_EnvProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_oneflow_EnvProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_oneflow_EnvProto_descriptor,
        new java.lang.String[] { "Machine", "CtrlPort", "DataPort", "CppLoggingConf", "CtrlBootstrapConf", "IsDefaultPhysicalEnv", });
    oneflow.CtrlBootstrap.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
