// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/job/job_set.proto

package org.oneflow.core.job;

/**
 * Protobuf type {@code oneflow.InterJobReuseMemStrategy}
 */
public  final class InterJobReuseMemStrategy extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:oneflow.InterJobReuseMemStrategy)
    InterJobReuseMemStrategyOrBuilder {
  // Use InterJobReuseMemStrategy.newBuilder() to construct.
  private InterJobReuseMemStrategy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InterJobReuseMemStrategy() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InterJobReuseMemStrategy(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.oneflow.core.job.ReuseMemPriorityStrategy.Builder subBuilder = null;
            if (strategyCaseCase_ == 1) {
              subBuilder = ((org.oneflow.core.job.ReuseMemPriorityStrategy) strategyCase_).toBuilder();
            }
            strategyCase_ =
                input.readMessage(org.oneflow.core.job.ReuseMemPriorityStrategy.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.oneflow.core.job.ReuseMemPriorityStrategy) strategyCase_);
              strategyCase_ = subBuilder.buildPartial();
            }
            strategyCaseCase_ = 1;
            break;
          }
          case 18: {
            org.oneflow.core.job.ParallelismPriorityStrategy.Builder subBuilder = null;
            if (strategyCaseCase_ == 2) {
              subBuilder = ((org.oneflow.core.job.ParallelismPriorityStrategy) strategyCase_).toBuilder();
            }
            strategyCase_ =
                input.readMessage(org.oneflow.core.job.ParallelismPriorityStrategy.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.oneflow.core.job.ParallelismPriorityStrategy) strategyCase_);
              strategyCase_ = subBuilder.buildPartial();
            }
            strategyCaseCase_ = 2;
            break;
          }
          case 26: {
            org.oneflow.core.job.CustomParallelismStrategy.Builder subBuilder = null;
            if (strategyCaseCase_ == 3) {
              subBuilder = ((org.oneflow.core.job.CustomParallelismStrategy) strategyCase_).toBuilder();
            }
            strategyCase_ =
                input.readMessage(org.oneflow.core.job.CustomParallelismStrategy.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.oneflow.core.job.CustomParallelismStrategy) strategyCase_);
              strategyCase_ = subBuilder.buildPartial();
            }
            strategyCaseCase_ = 3;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.oneflow.core.job.JobSetOuterClass.internal_static_oneflow_InterJobReuseMemStrategy_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.oneflow.core.job.JobSetOuterClass.internal_static_oneflow_InterJobReuseMemStrategy_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.oneflow.core.job.InterJobReuseMemStrategy.class, org.oneflow.core.job.InterJobReuseMemStrategy.Builder.class);
  }

  private int bitField0_;
  private int strategyCaseCase_ = 0;
  private java.lang.Object strategyCase_;
  public enum StrategyCaseCase
      implements com.google.protobuf.Internal.EnumLite {
    REUSE_MEM_PRIORITY(1),
    PARALLELISM_PRIORITY(2),
    CUSTOM_PARALLELISM(3),
    STRATEGYCASE_NOT_SET(0);
    private final int value;
    private StrategyCaseCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StrategyCaseCase valueOf(int value) {
      return forNumber(value);
    }

    public static StrategyCaseCase forNumber(int value) {
      switch (value) {
        case 1: return REUSE_MEM_PRIORITY;
        case 2: return PARALLELISM_PRIORITY;
        case 3: return CUSTOM_PARALLELISM;
        case 0: return STRATEGYCASE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public StrategyCaseCase
  getStrategyCaseCase() {
    return StrategyCaseCase.forNumber(
        strategyCaseCase_);
  }

  public static final int REUSE_MEM_PRIORITY_FIELD_NUMBER = 1;
  /**
   * <code>optional .oneflow.ReuseMemPriorityStrategy reuse_mem_priority = 1;</code>
   */
  public boolean hasReuseMemPriority() {
    return strategyCaseCase_ == 1;
  }
  /**
   * <code>optional .oneflow.ReuseMemPriorityStrategy reuse_mem_priority = 1;</code>
   */
  public org.oneflow.core.job.ReuseMemPriorityStrategy getReuseMemPriority() {
    if (strategyCaseCase_ == 1) {
       return (org.oneflow.core.job.ReuseMemPriorityStrategy) strategyCase_;
    }
    return org.oneflow.core.job.ReuseMemPriorityStrategy.getDefaultInstance();
  }
  /**
   * <code>optional .oneflow.ReuseMemPriorityStrategy reuse_mem_priority = 1;</code>
   */
  public org.oneflow.core.job.ReuseMemPriorityStrategyOrBuilder getReuseMemPriorityOrBuilder() {
    if (strategyCaseCase_ == 1) {
       return (org.oneflow.core.job.ReuseMemPriorityStrategy) strategyCase_;
    }
    return org.oneflow.core.job.ReuseMemPriorityStrategy.getDefaultInstance();
  }

  public static final int PARALLELISM_PRIORITY_FIELD_NUMBER = 2;
  /**
   * <code>optional .oneflow.ParallelismPriorityStrategy parallelism_priority = 2;</code>
   */
  public boolean hasParallelismPriority() {
    return strategyCaseCase_ == 2;
  }
  /**
   * <code>optional .oneflow.ParallelismPriorityStrategy parallelism_priority = 2;</code>
   */
  public org.oneflow.core.job.ParallelismPriorityStrategy getParallelismPriority() {
    if (strategyCaseCase_ == 2) {
       return (org.oneflow.core.job.ParallelismPriorityStrategy) strategyCase_;
    }
    return org.oneflow.core.job.ParallelismPriorityStrategy.getDefaultInstance();
  }
  /**
   * <code>optional .oneflow.ParallelismPriorityStrategy parallelism_priority = 2;</code>
   */
  public org.oneflow.core.job.ParallelismPriorityStrategyOrBuilder getParallelismPriorityOrBuilder() {
    if (strategyCaseCase_ == 2) {
       return (org.oneflow.core.job.ParallelismPriorityStrategy) strategyCase_;
    }
    return org.oneflow.core.job.ParallelismPriorityStrategy.getDefaultInstance();
  }

  public static final int CUSTOM_PARALLELISM_FIELD_NUMBER = 3;
  /**
   * <code>optional .oneflow.CustomParallelismStrategy custom_parallelism = 3;</code>
   */
  public boolean hasCustomParallelism() {
    return strategyCaseCase_ == 3;
  }
  /**
   * <code>optional .oneflow.CustomParallelismStrategy custom_parallelism = 3;</code>
   */
  public org.oneflow.core.job.CustomParallelismStrategy getCustomParallelism() {
    if (strategyCaseCase_ == 3) {
       return (org.oneflow.core.job.CustomParallelismStrategy) strategyCase_;
    }
    return org.oneflow.core.job.CustomParallelismStrategy.getDefaultInstance();
  }
  /**
   * <code>optional .oneflow.CustomParallelismStrategy custom_parallelism = 3;</code>
   */
  public org.oneflow.core.job.CustomParallelismStrategyOrBuilder getCustomParallelismOrBuilder() {
    if (strategyCaseCase_ == 3) {
       return (org.oneflow.core.job.CustomParallelismStrategy) strategyCase_;
    }
    return org.oneflow.core.job.CustomParallelismStrategy.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (strategyCaseCase_ == 1) {
      output.writeMessage(1, (org.oneflow.core.job.ReuseMemPriorityStrategy) strategyCase_);
    }
    if (strategyCaseCase_ == 2) {
      output.writeMessage(2, (org.oneflow.core.job.ParallelismPriorityStrategy) strategyCase_);
    }
    if (strategyCaseCase_ == 3) {
      output.writeMessage(3, (org.oneflow.core.job.CustomParallelismStrategy) strategyCase_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (strategyCaseCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (org.oneflow.core.job.ReuseMemPriorityStrategy) strategyCase_);
    }
    if (strategyCaseCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (org.oneflow.core.job.ParallelismPriorityStrategy) strategyCase_);
    }
    if (strategyCaseCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (org.oneflow.core.job.CustomParallelismStrategy) strategyCase_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.oneflow.core.job.InterJobReuseMemStrategy)) {
      return super.equals(obj);
    }
    org.oneflow.core.job.InterJobReuseMemStrategy other = (org.oneflow.core.job.InterJobReuseMemStrategy) obj;

    boolean result = true;
    result = result && getStrategyCaseCase().equals(
        other.getStrategyCaseCase());
    if (!result) return false;
    switch (strategyCaseCase_) {
      case 1:
        result = result && getReuseMemPriority()
            .equals(other.getReuseMemPriority());
        break;
      case 2:
        result = result && getParallelismPriority()
            .equals(other.getParallelismPriority());
        break;
      case 3:
        result = result && getCustomParallelism()
            .equals(other.getCustomParallelism());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    switch (strategyCaseCase_) {
      case 1:
        hash = (37 * hash) + REUSE_MEM_PRIORITY_FIELD_NUMBER;
        hash = (53 * hash) + getReuseMemPriority().hashCode();
        break;
      case 2:
        hash = (37 * hash) + PARALLELISM_PRIORITY_FIELD_NUMBER;
        hash = (53 * hash) + getParallelismPriority().hashCode();
        break;
      case 3:
        hash = (37 * hash) + CUSTOM_PARALLELISM_FIELD_NUMBER;
        hash = (53 * hash) + getCustomParallelism().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.oneflow.core.job.InterJobReuseMemStrategy parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.job.InterJobReuseMemStrategy parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.job.InterJobReuseMemStrategy parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.job.InterJobReuseMemStrategy parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.job.InterJobReuseMemStrategy parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.InterJobReuseMemStrategy parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.job.InterJobReuseMemStrategy parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.InterJobReuseMemStrategy parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.job.InterJobReuseMemStrategy parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.InterJobReuseMemStrategy parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.oneflow.core.job.InterJobReuseMemStrategy prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code oneflow.InterJobReuseMemStrategy}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:oneflow.InterJobReuseMemStrategy)
      org.oneflow.core.job.InterJobReuseMemStrategyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.oneflow.core.job.JobSetOuterClass.internal_static_oneflow_InterJobReuseMemStrategy_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.oneflow.core.job.JobSetOuterClass.internal_static_oneflow_InterJobReuseMemStrategy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.oneflow.core.job.InterJobReuseMemStrategy.class, org.oneflow.core.job.InterJobReuseMemStrategy.Builder.class);
    }

    // Construct using org.oneflow.core.job.InterJobReuseMemStrategy.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      strategyCaseCase_ = 0;
      strategyCase_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.oneflow.core.job.JobSetOuterClass.internal_static_oneflow_InterJobReuseMemStrategy_descriptor;
    }

    public org.oneflow.core.job.InterJobReuseMemStrategy getDefaultInstanceForType() {
      return org.oneflow.core.job.InterJobReuseMemStrategy.getDefaultInstance();
    }

    public org.oneflow.core.job.InterJobReuseMemStrategy build() {
      org.oneflow.core.job.InterJobReuseMemStrategy result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.oneflow.core.job.InterJobReuseMemStrategy buildPartial() {
      org.oneflow.core.job.InterJobReuseMemStrategy result = new org.oneflow.core.job.InterJobReuseMemStrategy(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (strategyCaseCase_ == 1) {
        if (reuseMemPriorityBuilder_ == null) {
          result.strategyCase_ = strategyCase_;
        } else {
          result.strategyCase_ = reuseMemPriorityBuilder_.build();
        }
      }
      if (strategyCaseCase_ == 2) {
        if (parallelismPriorityBuilder_ == null) {
          result.strategyCase_ = strategyCase_;
        } else {
          result.strategyCase_ = parallelismPriorityBuilder_.build();
        }
      }
      if (strategyCaseCase_ == 3) {
        if (customParallelismBuilder_ == null) {
          result.strategyCase_ = strategyCase_;
        } else {
          result.strategyCase_ = customParallelismBuilder_.build();
        }
      }
      result.bitField0_ = to_bitField0_;
      result.strategyCaseCase_ = strategyCaseCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.oneflow.core.job.InterJobReuseMemStrategy) {
        return mergeFrom((org.oneflow.core.job.InterJobReuseMemStrategy)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.oneflow.core.job.InterJobReuseMemStrategy other) {
      if (other == org.oneflow.core.job.InterJobReuseMemStrategy.getDefaultInstance()) return this;
      switch (other.getStrategyCaseCase()) {
        case REUSE_MEM_PRIORITY: {
          mergeReuseMemPriority(other.getReuseMemPriority());
          break;
        }
        case PARALLELISM_PRIORITY: {
          mergeParallelismPriority(other.getParallelismPriority());
          break;
        }
        case CUSTOM_PARALLELISM: {
          mergeCustomParallelism(other.getCustomParallelism());
          break;
        }
        case STRATEGYCASE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.oneflow.core.job.InterJobReuseMemStrategy parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.oneflow.core.job.InterJobReuseMemStrategy) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int strategyCaseCase_ = 0;
    private java.lang.Object strategyCase_;
    public StrategyCaseCase
        getStrategyCaseCase() {
      return StrategyCaseCase.forNumber(
          strategyCaseCase_);
    }

    public Builder clearStrategyCase() {
      strategyCaseCase_ = 0;
      strategyCase_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        org.oneflow.core.job.ReuseMemPriorityStrategy, org.oneflow.core.job.ReuseMemPriorityStrategy.Builder, org.oneflow.core.job.ReuseMemPriorityStrategyOrBuilder> reuseMemPriorityBuilder_;
    /**
     * <code>optional .oneflow.ReuseMemPriorityStrategy reuse_mem_priority = 1;</code>
     */
    public boolean hasReuseMemPriority() {
      return strategyCaseCase_ == 1;
    }
    /**
     * <code>optional .oneflow.ReuseMemPriorityStrategy reuse_mem_priority = 1;</code>
     */
    public org.oneflow.core.job.ReuseMemPriorityStrategy getReuseMemPriority() {
      if (reuseMemPriorityBuilder_ == null) {
        if (strategyCaseCase_ == 1) {
          return (org.oneflow.core.job.ReuseMemPriorityStrategy) strategyCase_;
        }
        return org.oneflow.core.job.ReuseMemPriorityStrategy.getDefaultInstance();
      } else {
        if (strategyCaseCase_ == 1) {
          return reuseMemPriorityBuilder_.getMessage();
        }
        return org.oneflow.core.job.ReuseMemPriorityStrategy.getDefaultInstance();
      }
    }
    /**
     * <code>optional .oneflow.ReuseMemPriorityStrategy reuse_mem_priority = 1;</code>
     */
    public Builder setReuseMemPriority(org.oneflow.core.job.ReuseMemPriorityStrategy value) {
      if (reuseMemPriorityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        strategyCase_ = value;
        onChanged();
      } else {
        reuseMemPriorityBuilder_.setMessage(value);
      }
      strategyCaseCase_ = 1;
      return this;
    }
    /**
     * <code>optional .oneflow.ReuseMemPriorityStrategy reuse_mem_priority = 1;</code>
     */
    public Builder setReuseMemPriority(
        org.oneflow.core.job.ReuseMemPriorityStrategy.Builder builderForValue) {
      if (reuseMemPriorityBuilder_ == null) {
        strategyCase_ = builderForValue.build();
        onChanged();
      } else {
        reuseMemPriorityBuilder_.setMessage(builderForValue.build());
      }
      strategyCaseCase_ = 1;
      return this;
    }
    /**
     * <code>optional .oneflow.ReuseMemPriorityStrategy reuse_mem_priority = 1;</code>
     */
    public Builder mergeReuseMemPriority(org.oneflow.core.job.ReuseMemPriorityStrategy value) {
      if (reuseMemPriorityBuilder_ == null) {
        if (strategyCaseCase_ == 1 &&
            strategyCase_ != org.oneflow.core.job.ReuseMemPriorityStrategy.getDefaultInstance()) {
          strategyCase_ = org.oneflow.core.job.ReuseMemPriorityStrategy.newBuilder((org.oneflow.core.job.ReuseMemPriorityStrategy) strategyCase_)
              .mergeFrom(value).buildPartial();
        } else {
          strategyCase_ = value;
        }
        onChanged();
      } else {
        if (strategyCaseCase_ == 1) {
          reuseMemPriorityBuilder_.mergeFrom(value);
        }
        reuseMemPriorityBuilder_.setMessage(value);
      }
      strategyCaseCase_ = 1;
      return this;
    }
    /**
     * <code>optional .oneflow.ReuseMemPriorityStrategy reuse_mem_priority = 1;</code>
     */
    public Builder clearReuseMemPriority() {
      if (reuseMemPriorityBuilder_ == null) {
        if (strategyCaseCase_ == 1) {
          strategyCaseCase_ = 0;
          strategyCase_ = null;
          onChanged();
        }
      } else {
        if (strategyCaseCase_ == 1) {
          strategyCaseCase_ = 0;
          strategyCase_ = null;
        }
        reuseMemPriorityBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .oneflow.ReuseMemPriorityStrategy reuse_mem_priority = 1;</code>
     */
    public org.oneflow.core.job.ReuseMemPriorityStrategy.Builder getReuseMemPriorityBuilder() {
      return getReuseMemPriorityFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .oneflow.ReuseMemPriorityStrategy reuse_mem_priority = 1;</code>
     */
    public org.oneflow.core.job.ReuseMemPriorityStrategyOrBuilder getReuseMemPriorityOrBuilder() {
      if ((strategyCaseCase_ == 1) && (reuseMemPriorityBuilder_ != null)) {
        return reuseMemPriorityBuilder_.getMessageOrBuilder();
      } else {
        if (strategyCaseCase_ == 1) {
          return (org.oneflow.core.job.ReuseMemPriorityStrategy) strategyCase_;
        }
        return org.oneflow.core.job.ReuseMemPriorityStrategy.getDefaultInstance();
      }
    }
    /**
     * <code>optional .oneflow.ReuseMemPriorityStrategy reuse_mem_priority = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.oneflow.core.job.ReuseMemPriorityStrategy, org.oneflow.core.job.ReuseMemPriorityStrategy.Builder, org.oneflow.core.job.ReuseMemPriorityStrategyOrBuilder> 
        getReuseMemPriorityFieldBuilder() {
      if (reuseMemPriorityBuilder_ == null) {
        if (!(strategyCaseCase_ == 1)) {
          strategyCase_ = org.oneflow.core.job.ReuseMemPriorityStrategy.getDefaultInstance();
        }
        reuseMemPriorityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.oneflow.core.job.ReuseMemPriorityStrategy, org.oneflow.core.job.ReuseMemPriorityStrategy.Builder, org.oneflow.core.job.ReuseMemPriorityStrategyOrBuilder>(
                (org.oneflow.core.job.ReuseMemPriorityStrategy) strategyCase_,
                getParentForChildren(),
                isClean());
        strategyCase_ = null;
      }
      strategyCaseCase_ = 1;
      onChanged();;
      return reuseMemPriorityBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.oneflow.core.job.ParallelismPriorityStrategy, org.oneflow.core.job.ParallelismPriorityStrategy.Builder, org.oneflow.core.job.ParallelismPriorityStrategyOrBuilder> parallelismPriorityBuilder_;
    /**
     * <code>optional .oneflow.ParallelismPriorityStrategy parallelism_priority = 2;</code>
     */
    public boolean hasParallelismPriority() {
      return strategyCaseCase_ == 2;
    }
    /**
     * <code>optional .oneflow.ParallelismPriorityStrategy parallelism_priority = 2;</code>
     */
    public org.oneflow.core.job.ParallelismPriorityStrategy getParallelismPriority() {
      if (parallelismPriorityBuilder_ == null) {
        if (strategyCaseCase_ == 2) {
          return (org.oneflow.core.job.ParallelismPriorityStrategy) strategyCase_;
        }
        return org.oneflow.core.job.ParallelismPriorityStrategy.getDefaultInstance();
      } else {
        if (strategyCaseCase_ == 2) {
          return parallelismPriorityBuilder_.getMessage();
        }
        return org.oneflow.core.job.ParallelismPriorityStrategy.getDefaultInstance();
      }
    }
    /**
     * <code>optional .oneflow.ParallelismPriorityStrategy parallelism_priority = 2;</code>
     */
    public Builder setParallelismPriority(org.oneflow.core.job.ParallelismPriorityStrategy value) {
      if (parallelismPriorityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        strategyCase_ = value;
        onChanged();
      } else {
        parallelismPriorityBuilder_.setMessage(value);
      }
      strategyCaseCase_ = 2;
      return this;
    }
    /**
     * <code>optional .oneflow.ParallelismPriorityStrategy parallelism_priority = 2;</code>
     */
    public Builder setParallelismPriority(
        org.oneflow.core.job.ParallelismPriorityStrategy.Builder builderForValue) {
      if (parallelismPriorityBuilder_ == null) {
        strategyCase_ = builderForValue.build();
        onChanged();
      } else {
        parallelismPriorityBuilder_.setMessage(builderForValue.build());
      }
      strategyCaseCase_ = 2;
      return this;
    }
    /**
     * <code>optional .oneflow.ParallelismPriorityStrategy parallelism_priority = 2;</code>
     */
    public Builder mergeParallelismPriority(org.oneflow.core.job.ParallelismPriorityStrategy value) {
      if (parallelismPriorityBuilder_ == null) {
        if (strategyCaseCase_ == 2 &&
            strategyCase_ != org.oneflow.core.job.ParallelismPriorityStrategy.getDefaultInstance()) {
          strategyCase_ = org.oneflow.core.job.ParallelismPriorityStrategy.newBuilder((org.oneflow.core.job.ParallelismPriorityStrategy) strategyCase_)
              .mergeFrom(value).buildPartial();
        } else {
          strategyCase_ = value;
        }
        onChanged();
      } else {
        if (strategyCaseCase_ == 2) {
          parallelismPriorityBuilder_.mergeFrom(value);
        }
        parallelismPriorityBuilder_.setMessage(value);
      }
      strategyCaseCase_ = 2;
      return this;
    }
    /**
     * <code>optional .oneflow.ParallelismPriorityStrategy parallelism_priority = 2;</code>
     */
    public Builder clearParallelismPriority() {
      if (parallelismPriorityBuilder_ == null) {
        if (strategyCaseCase_ == 2) {
          strategyCaseCase_ = 0;
          strategyCase_ = null;
          onChanged();
        }
      } else {
        if (strategyCaseCase_ == 2) {
          strategyCaseCase_ = 0;
          strategyCase_ = null;
        }
        parallelismPriorityBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .oneflow.ParallelismPriorityStrategy parallelism_priority = 2;</code>
     */
    public org.oneflow.core.job.ParallelismPriorityStrategy.Builder getParallelismPriorityBuilder() {
      return getParallelismPriorityFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .oneflow.ParallelismPriorityStrategy parallelism_priority = 2;</code>
     */
    public org.oneflow.core.job.ParallelismPriorityStrategyOrBuilder getParallelismPriorityOrBuilder() {
      if ((strategyCaseCase_ == 2) && (parallelismPriorityBuilder_ != null)) {
        return parallelismPriorityBuilder_.getMessageOrBuilder();
      } else {
        if (strategyCaseCase_ == 2) {
          return (org.oneflow.core.job.ParallelismPriorityStrategy) strategyCase_;
        }
        return org.oneflow.core.job.ParallelismPriorityStrategy.getDefaultInstance();
      }
    }
    /**
     * <code>optional .oneflow.ParallelismPriorityStrategy parallelism_priority = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.oneflow.core.job.ParallelismPriorityStrategy, org.oneflow.core.job.ParallelismPriorityStrategy.Builder, org.oneflow.core.job.ParallelismPriorityStrategyOrBuilder> 
        getParallelismPriorityFieldBuilder() {
      if (parallelismPriorityBuilder_ == null) {
        if (!(strategyCaseCase_ == 2)) {
          strategyCase_ = org.oneflow.core.job.ParallelismPriorityStrategy.getDefaultInstance();
        }
        parallelismPriorityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.oneflow.core.job.ParallelismPriorityStrategy, org.oneflow.core.job.ParallelismPriorityStrategy.Builder, org.oneflow.core.job.ParallelismPriorityStrategyOrBuilder>(
                (org.oneflow.core.job.ParallelismPriorityStrategy) strategyCase_,
                getParentForChildren(),
                isClean());
        strategyCase_ = null;
      }
      strategyCaseCase_ = 2;
      onChanged();;
      return parallelismPriorityBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.oneflow.core.job.CustomParallelismStrategy, org.oneflow.core.job.CustomParallelismStrategy.Builder, org.oneflow.core.job.CustomParallelismStrategyOrBuilder> customParallelismBuilder_;
    /**
     * <code>optional .oneflow.CustomParallelismStrategy custom_parallelism = 3;</code>
     */
    public boolean hasCustomParallelism() {
      return strategyCaseCase_ == 3;
    }
    /**
     * <code>optional .oneflow.CustomParallelismStrategy custom_parallelism = 3;</code>
     */
    public org.oneflow.core.job.CustomParallelismStrategy getCustomParallelism() {
      if (customParallelismBuilder_ == null) {
        if (strategyCaseCase_ == 3) {
          return (org.oneflow.core.job.CustomParallelismStrategy) strategyCase_;
        }
        return org.oneflow.core.job.CustomParallelismStrategy.getDefaultInstance();
      } else {
        if (strategyCaseCase_ == 3) {
          return customParallelismBuilder_.getMessage();
        }
        return org.oneflow.core.job.CustomParallelismStrategy.getDefaultInstance();
      }
    }
    /**
     * <code>optional .oneflow.CustomParallelismStrategy custom_parallelism = 3;</code>
     */
    public Builder setCustomParallelism(org.oneflow.core.job.CustomParallelismStrategy value) {
      if (customParallelismBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        strategyCase_ = value;
        onChanged();
      } else {
        customParallelismBuilder_.setMessage(value);
      }
      strategyCaseCase_ = 3;
      return this;
    }
    /**
     * <code>optional .oneflow.CustomParallelismStrategy custom_parallelism = 3;</code>
     */
    public Builder setCustomParallelism(
        org.oneflow.core.job.CustomParallelismStrategy.Builder builderForValue) {
      if (customParallelismBuilder_ == null) {
        strategyCase_ = builderForValue.build();
        onChanged();
      } else {
        customParallelismBuilder_.setMessage(builderForValue.build());
      }
      strategyCaseCase_ = 3;
      return this;
    }
    /**
     * <code>optional .oneflow.CustomParallelismStrategy custom_parallelism = 3;</code>
     */
    public Builder mergeCustomParallelism(org.oneflow.core.job.CustomParallelismStrategy value) {
      if (customParallelismBuilder_ == null) {
        if (strategyCaseCase_ == 3 &&
            strategyCase_ != org.oneflow.core.job.CustomParallelismStrategy.getDefaultInstance()) {
          strategyCase_ = org.oneflow.core.job.CustomParallelismStrategy.newBuilder((org.oneflow.core.job.CustomParallelismStrategy) strategyCase_)
              .mergeFrom(value).buildPartial();
        } else {
          strategyCase_ = value;
        }
        onChanged();
      } else {
        if (strategyCaseCase_ == 3) {
          customParallelismBuilder_.mergeFrom(value);
        }
        customParallelismBuilder_.setMessage(value);
      }
      strategyCaseCase_ = 3;
      return this;
    }
    /**
     * <code>optional .oneflow.CustomParallelismStrategy custom_parallelism = 3;</code>
     */
    public Builder clearCustomParallelism() {
      if (customParallelismBuilder_ == null) {
        if (strategyCaseCase_ == 3) {
          strategyCaseCase_ = 0;
          strategyCase_ = null;
          onChanged();
        }
      } else {
        if (strategyCaseCase_ == 3) {
          strategyCaseCase_ = 0;
          strategyCase_ = null;
        }
        customParallelismBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .oneflow.CustomParallelismStrategy custom_parallelism = 3;</code>
     */
    public org.oneflow.core.job.CustomParallelismStrategy.Builder getCustomParallelismBuilder() {
      return getCustomParallelismFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .oneflow.CustomParallelismStrategy custom_parallelism = 3;</code>
     */
    public org.oneflow.core.job.CustomParallelismStrategyOrBuilder getCustomParallelismOrBuilder() {
      if ((strategyCaseCase_ == 3) && (customParallelismBuilder_ != null)) {
        return customParallelismBuilder_.getMessageOrBuilder();
      } else {
        if (strategyCaseCase_ == 3) {
          return (org.oneflow.core.job.CustomParallelismStrategy) strategyCase_;
        }
        return org.oneflow.core.job.CustomParallelismStrategy.getDefaultInstance();
      }
    }
    /**
     * <code>optional .oneflow.CustomParallelismStrategy custom_parallelism = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.oneflow.core.job.CustomParallelismStrategy, org.oneflow.core.job.CustomParallelismStrategy.Builder, org.oneflow.core.job.CustomParallelismStrategyOrBuilder> 
        getCustomParallelismFieldBuilder() {
      if (customParallelismBuilder_ == null) {
        if (!(strategyCaseCase_ == 3)) {
          strategyCase_ = org.oneflow.core.job.CustomParallelismStrategy.getDefaultInstance();
        }
        customParallelismBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.oneflow.core.job.CustomParallelismStrategy, org.oneflow.core.job.CustomParallelismStrategy.Builder, org.oneflow.core.job.CustomParallelismStrategyOrBuilder>(
                (org.oneflow.core.job.CustomParallelismStrategy) strategyCase_,
                getParentForChildren(),
                isClean());
        strategyCase_ = null;
      }
      strategyCaseCase_ = 3;
      onChanged();;
      return customParallelismBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:oneflow.InterJobReuseMemStrategy)
  }

  // @@protoc_insertion_point(class_scope:oneflow.InterJobReuseMemStrategy)
  private static final org.oneflow.core.job.InterJobReuseMemStrategy DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.oneflow.core.job.InterJobReuseMemStrategy();
  }

  public static org.oneflow.core.job.InterJobReuseMemStrategy getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<InterJobReuseMemStrategy>
      PARSER = new com.google.protobuf.AbstractParser<InterJobReuseMemStrategy>() {
    public InterJobReuseMemStrategy parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new InterJobReuseMemStrategy(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InterJobReuseMemStrategy> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InterJobReuseMemStrategy> getParserForType() {
    return PARSER;
  }

  public org.oneflow.core.job.InterJobReuseMemStrategy getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

