// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/job/learning_rate_schedule_conf.proto

package org.oneflow.core.job;

/**
 * Protobuf type {@code oneflow.InverseTimeDecayConf}
 */
public  final class InverseTimeDecayConf extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:oneflow.InverseTimeDecayConf)
    InverseTimeDecayConfOrBuilder {
  // Use InverseTimeDecayConf.newBuilder() to construct.
  private InverseTimeDecayConf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InverseTimeDecayConf() {
    decayBatches_ = 0L;
    decayRate_ = 0D;
    staircase_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InverseTimeDecayConf(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            decayBatches_ = input.readInt64();
            break;
          }
          case 17: {
            bitField0_ |= 0x00000002;
            decayRate_ = input.readDouble();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            staircase_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.oneflow.core.job.LearningRateScheduleConf.internal_static_oneflow_InverseTimeDecayConf_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.oneflow.core.job.LearningRateScheduleConf.internal_static_oneflow_InverseTimeDecayConf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.oneflow.core.job.InverseTimeDecayConf.class, org.oneflow.core.job.InverseTimeDecayConf.Builder.class);
  }

  private int bitField0_;
  public static final int DECAY_BATCHES_FIELD_NUMBER = 1;
  private long decayBatches_;
  /**
   * <code>required int64 decay_batches = 1;</code>
   */
  public boolean hasDecayBatches() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int64 decay_batches = 1;</code>
   */
  public long getDecayBatches() {
    return decayBatches_;
  }

  public static final int DECAY_RATE_FIELD_NUMBER = 2;
  private double decayRate_;
  /**
   * <code>required double decay_rate = 2;</code>
   */
  public boolean hasDecayRate() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required double decay_rate = 2;</code>
   */
  public double getDecayRate() {
    return decayRate_;
  }

  public static final int STAIRCASE_FIELD_NUMBER = 3;
  private boolean staircase_;
  /**
   * <code>optional bool staircase = 3 [default = false];</code>
   */
  public boolean hasStaircase() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional bool staircase = 3 [default = false];</code>
   */
  public boolean getStaircase() {
    return staircase_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasDecayBatches()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDecayRate()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, decayBatches_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeDouble(2, decayRate_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBool(3, staircase_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, decayBatches_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, decayRate_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, staircase_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.oneflow.core.job.InverseTimeDecayConf)) {
      return super.equals(obj);
    }
    org.oneflow.core.job.InverseTimeDecayConf other = (org.oneflow.core.job.InverseTimeDecayConf) obj;

    boolean result = true;
    result = result && (hasDecayBatches() == other.hasDecayBatches());
    if (hasDecayBatches()) {
      result = result && (getDecayBatches()
          == other.getDecayBatches());
    }
    result = result && (hasDecayRate() == other.hasDecayRate());
    if (hasDecayRate()) {
      result = result && (
          java.lang.Double.doubleToLongBits(getDecayRate())
          == java.lang.Double.doubleToLongBits(
              other.getDecayRate()));
    }
    result = result && (hasStaircase() == other.hasStaircase());
    if (hasStaircase()) {
      result = result && (getStaircase()
          == other.getStaircase());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasDecayBatches()) {
      hash = (37 * hash) + DECAY_BATCHES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDecayBatches());
    }
    if (hasDecayRate()) {
      hash = (37 * hash) + DECAY_RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDecayRate()));
    }
    if (hasStaircase()) {
      hash = (37 * hash) + STAIRCASE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStaircase());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.oneflow.core.job.InverseTimeDecayConf parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.job.InverseTimeDecayConf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.job.InverseTimeDecayConf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.job.InverseTimeDecayConf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.job.InverseTimeDecayConf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.InverseTimeDecayConf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.job.InverseTimeDecayConf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.InverseTimeDecayConf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.job.InverseTimeDecayConf parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.InverseTimeDecayConf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.oneflow.core.job.InverseTimeDecayConf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code oneflow.InverseTimeDecayConf}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:oneflow.InverseTimeDecayConf)
      org.oneflow.core.job.InverseTimeDecayConfOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.oneflow.core.job.LearningRateScheduleConf.internal_static_oneflow_InverseTimeDecayConf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.oneflow.core.job.LearningRateScheduleConf.internal_static_oneflow_InverseTimeDecayConf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.oneflow.core.job.InverseTimeDecayConf.class, org.oneflow.core.job.InverseTimeDecayConf.Builder.class);
    }

    // Construct using org.oneflow.core.job.InverseTimeDecayConf.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      decayBatches_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      decayRate_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000002);
      staircase_ = false;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.oneflow.core.job.LearningRateScheduleConf.internal_static_oneflow_InverseTimeDecayConf_descriptor;
    }

    public org.oneflow.core.job.InverseTimeDecayConf getDefaultInstanceForType() {
      return org.oneflow.core.job.InverseTimeDecayConf.getDefaultInstance();
    }

    public org.oneflow.core.job.InverseTimeDecayConf build() {
      org.oneflow.core.job.InverseTimeDecayConf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.oneflow.core.job.InverseTimeDecayConf buildPartial() {
      org.oneflow.core.job.InverseTimeDecayConf result = new org.oneflow.core.job.InverseTimeDecayConf(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.decayBatches_ = decayBatches_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.decayRate_ = decayRate_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.staircase_ = staircase_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.oneflow.core.job.InverseTimeDecayConf) {
        return mergeFrom((org.oneflow.core.job.InverseTimeDecayConf)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.oneflow.core.job.InverseTimeDecayConf other) {
      if (other == org.oneflow.core.job.InverseTimeDecayConf.getDefaultInstance()) return this;
      if (other.hasDecayBatches()) {
        setDecayBatches(other.getDecayBatches());
      }
      if (other.hasDecayRate()) {
        setDecayRate(other.getDecayRate());
      }
      if (other.hasStaircase()) {
        setStaircase(other.getStaircase());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasDecayBatches()) {
        return false;
      }
      if (!hasDecayRate()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.oneflow.core.job.InverseTimeDecayConf parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.oneflow.core.job.InverseTimeDecayConf) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long decayBatches_ ;
    /**
     * <code>required int64 decay_batches = 1;</code>
     */
    public boolean hasDecayBatches() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 decay_batches = 1;</code>
     */
    public long getDecayBatches() {
      return decayBatches_;
    }
    /**
     * <code>required int64 decay_batches = 1;</code>
     */
    public Builder setDecayBatches(long value) {
      bitField0_ |= 0x00000001;
      decayBatches_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 decay_batches = 1;</code>
     */
    public Builder clearDecayBatches() {
      bitField0_ = (bitField0_ & ~0x00000001);
      decayBatches_ = 0L;
      onChanged();
      return this;
    }

    private double decayRate_ ;
    /**
     * <code>required double decay_rate = 2;</code>
     */
    public boolean hasDecayRate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double decay_rate = 2;</code>
     */
    public double getDecayRate() {
      return decayRate_;
    }
    /**
     * <code>required double decay_rate = 2;</code>
     */
    public Builder setDecayRate(double value) {
      bitField0_ |= 0x00000002;
      decayRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required double decay_rate = 2;</code>
     */
    public Builder clearDecayRate() {
      bitField0_ = (bitField0_ & ~0x00000002);
      decayRate_ = 0D;
      onChanged();
      return this;
    }

    private boolean staircase_ ;
    /**
     * <code>optional bool staircase = 3 [default = false];</code>
     */
    public boolean hasStaircase() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool staircase = 3 [default = false];</code>
     */
    public boolean getStaircase() {
      return staircase_;
    }
    /**
     * <code>optional bool staircase = 3 [default = false];</code>
     */
    public Builder setStaircase(boolean value) {
      bitField0_ |= 0x00000004;
      staircase_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool staircase = 3 [default = false];</code>
     */
    public Builder clearStaircase() {
      bitField0_ = (bitField0_ & ~0x00000004);
      staircase_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:oneflow.InverseTimeDecayConf)
  }

  // @@protoc_insertion_point(class_scope:oneflow.InverseTimeDecayConf)
  private static final org.oneflow.core.job.InverseTimeDecayConf DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.oneflow.core.job.InverseTimeDecayConf();
  }

  public static org.oneflow.core.job.InverseTimeDecayConf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<InverseTimeDecayConf>
      PARSER = new com.google.protobuf.AbstractParser<InverseTimeDecayConf>() {
    public InverseTimeDecayConf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new InverseTimeDecayConf(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InverseTimeDecayConf> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InverseTimeDecayConf> getParserForType() {
    return PARSER;
  }

  public org.oneflow.core.job.InverseTimeDecayConf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

