// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/job/job_conf.proto

package org.oneflow.core.job;

public interface LARSModelUpdateConfOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.LARSModelUpdateConf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional float momentum_beta = 1 [default = 0.9];</code>
   */
  boolean hasMomentumBeta();
  /**
   * <code>optional float momentum_beta = 1 [default = 0.9];</code>
   */
  float getMomentumBeta();

  /**
   * <code>optional float epsilon = 2 [default = 1e-09];</code>
   */
  boolean hasEpsilon();
  /**
   * <code>optional float epsilon = 2 [default = 1e-09];</code>
   */
  float getEpsilon();

  /**
   * <code>optional float lars_coefficient = 3 [default = 0.0001];</code>
   */
  boolean hasLarsCoefficient();
  /**
   * <code>optional float lars_coefficient = 3 [default = 0.0001];</code>
   */
  float getLarsCoefficient();
}
