// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/job/job_conf.proto

package org.oneflow.core.job;

/**
 * Protobuf type {@code oneflow.MemoryAllocationAlgorithmConf}
 */
public  final class MemoryAllocationAlgorithmConf extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:oneflow.MemoryAllocationAlgorithmConf)
    MemoryAllocationAlgorithmConfOrBuilder {
  // Use MemoryAllocationAlgorithmConf.newBuilder() to construct.
  private MemoryAllocationAlgorithmConf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MemoryAllocationAlgorithmConf() {
    useMemSizeFirstAlgo_ = true;
    useMutualExclusionFirstAlgo_ = true;
    useTimeLineAlgo_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MemoryAllocationAlgorithmConf(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            useMemSizeFirstAlgo_ = input.readBool();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            useMutualExclusionFirstAlgo_ = input.readBool();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            useTimeLineAlgo_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.oneflow.core.job.JobConf.internal_static_oneflow_MemoryAllocationAlgorithmConf_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.oneflow.core.job.JobConf.internal_static_oneflow_MemoryAllocationAlgorithmConf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.oneflow.core.job.MemoryAllocationAlgorithmConf.class, org.oneflow.core.job.MemoryAllocationAlgorithmConf.Builder.class);
  }

  private int bitField0_;
  public static final int USE_MEM_SIZE_FIRST_ALGO_FIELD_NUMBER = 1;
  private boolean useMemSizeFirstAlgo_;
  /**
   * <code>optional bool use_mem_size_first_algo = 1 [default = true];</code>
   */
  public boolean hasUseMemSizeFirstAlgo() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional bool use_mem_size_first_algo = 1 [default = true];</code>
   */
  public boolean getUseMemSizeFirstAlgo() {
    return useMemSizeFirstAlgo_;
  }

  public static final int USE_MUTUAL_EXCLUSION_FIRST_ALGO_FIELD_NUMBER = 2;
  private boolean useMutualExclusionFirstAlgo_;
  /**
   * <code>optional bool use_mutual_exclusion_first_algo = 2 [default = true];</code>
   */
  public boolean hasUseMutualExclusionFirstAlgo() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional bool use_mutual_exclusion_first_algo = 2 [default = true];</code>
   */
  public boolean getUseMutualExclusionFirstAlgo() {
    return useMutualExclusionFirstAlgo_;
  }

  public static final int USE_TIME_LINE_ALGO_FIELD_NUMBER = 3;
  private boolean useTimeLineAlgo_;
  /**
   * <code>optional bool use_time_line_algo = 3 [default = false];</code>
   */
  public boolean hasUseTimeLineAlgo() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional bool use_time_line_algo = 3 [default = false];</code>
   */
  public boolean getUseTimeLineAlgo() {
    return useTimeLineAlgo_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBool(1, useMemSizeFirstAlgo_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBool(2, useMutualExclusionFirstAlgo_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBool(3, useTimeLineAlgo_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, useMemSizeFirstAlgo_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, useMutualExclusionFirstAlgo_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, useTimeLineAlgo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.oneflow.core.job.MemoryAllocationAlgorithmConf)) {
      return super.equals(obj);
    }
    org.oneflow.core.job.MemoryAllocationAlgorithmConf other = (org.oneflow.core.job.MemoryAllocationAlgorithmConf) obj;

    boolean result = true;
    result = result && (hasUseMemSizeFirstAlgo() == other.hasUseMemSizeFirstAlgo());
    if (hasUseMemSizeFirstAlgo()) {
      result = result && (getUseMemSizeFirstAlgo()
          == other.getUseMemSizeFirstAlgo());
    }
    result = result && (hasUseMutualExclusionFirstAlgo() == other.hasUseMutualExclusionFirstAlgo());
    if (hasUseMutualExclusionFirstAlgo()) {
      result = result && (getUseMutualExclusionFirstAlgo()
          == other.getUseMutualExclusionFirstAlgo());
    }
    result = result && (hasUseTimeLineAlgo() == other.hasUseTimeLineAlgo());
    if (hasUseTimeLineAlgo()) {
      result = result && (getUseTimeLineAlgo()
          == other.getUseTimeLineAlgo());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasUseMemSizeFirstAlgo()) {
      hash = (37 * hash) + USE_MEM_SIZE_FIRST_ALGO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUseMemSizeFirstAlgo());
    }
    if (hasUseMutualExclusionFirstAlgo()) {
      hash = (37 * hash) + USE_MUTUAL_EXCLUSION_FIRST_ALGO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUseMutualExclusionFirstAlgo());
    }
    if (hasUseTimeLineAlgo()) {
      hash = (37 * hash) + USE_TIME_LINE_ALGO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUseTimeLineAlgo());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.oneflow.core.job.MemoryAllocationAlgorithmConf parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.job.MemoryAllocationAlgorithmConf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.job.MemoryAllocationAlgorithmConf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.job.MemoryAllocationAlgorithmConf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.job.MemoryAllocationAlgorithmConf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.MemoryAllocationAlgorithmConf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.job.MemoryAllocationAlgorithmConf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.MemoryAllocationAlgorithmConf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.job.MemoryAllocationAlgorithmConf parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.MemoryAllocationAlgorithmConf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.oneflow.core.job.MemoryAllocationAlgorithmConf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code oneflow.MemoryAllocationAlgorithmConf}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:oneflow.MemoryAllocationAlgorithmConf)
      org.oneflow.core.job.MemoryAllocationAlgorithmConfOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.oneflow.core.job.JobConf.internal_static_oneflow_MemoryAllocationAlgorithmConf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.oneflow.core.job.JobConf.internal_static_oneflow_MemoryAllocationAlgorithmConf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.oneflow.core.job.MemoryAllocationAlgorithmConf.class, org.oneflow.core.job.MemoryAllocationAlgorithmConf.Builder.class);
    }

    // Construct using org.oneflow.core.job.MemoryAllocationAlgorithmConf.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      useMemSizeFirstAlgo_ = true;
      bitField0_ = (bitField0_ & ~0x00000001);
      useMutualExclusionFirstAlgo_ = true;
      bitField0_ = (bitField0_ & ~0x00000002);
      useTimeLineAlgo_ = false;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.oneflow.core.job.JobConf.internal_static_oneflow_MemoryAllocationAlgorithmConf_descriptor;
    }

    public org.oneflow.core.job.MemoryAllocationAlgorithmConf getDefaultInstanceForType() {
      return org.oneflow.core.job.MemoryAllocationAlgorithmConf.getDefaultInstance();
    }

    public org.oneflow.core.job.MemoryAllocationAlgorithmConf build() {
      org.oneflow.core.job.MemoryAllocationAlgorithmConf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.oneflow.core.job.MemoryAllocationAlgorithmConf buildPartial() {
      org.oneflow.core.job.MemoryAllocationAlgorithmConf result = new org.oneflow.core.job.MemoryAllocationAlgorithmConf(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.useMemSizeFirstAlgo_ = useMemSizeFirstAlgo_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.useMutualExclusionFirstAlgo_ = useMutualExclusionFirstAlgo_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.useTimeLineAlgo_ = useTimeLineAlgo_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.oneflow.core.job.MemoryAllocationAlgorithmConf) {
        return mergeFrom((org.oneflow.core.job.MemoryAllocationAlgorithmConf)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.oneflow.core.job.MemoryAllocationAlgorithmConf other) {
      if (other == org.oneflow.core.job.MemoryAllocationAlgorithmConf.getDefaultInstance()) return this;
      if (other.hasUseMemSizeFirstAlgo()) {
        setUseMemSizeFirstAlgo(other.getUseMemSizeFirstAlgo());
      }
      if (other.hasUseMutualExclusionFirstAlgo()) {
        setUseMutualExclusionFirstAlgo(other.getUseMutualExclusionFirstAlgo());
      }
      if (other.hasUseTimeLineAlgo()) {
        setUseTimeLineAlgo(other.getUseTimeLineAlgo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.oneflow.core.job.MemoryAllocationAlgorithmConf parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.oneflow.core.job.MemoryAllocationAlgorithmConf) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean useMemSizeFirstAlgo_ = true;
    /**
     * <code>optional bool use_mem_size_first_algo = 1 [default = true];</code>
     */
    public boolean hasUseMemSizeFirstAlgo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool use_mem_size_first_algo = 1 [default = true];</code>
     */
    public boolean getUseMemSizeFirstAlgo() {
      return useMemSizeFirstAlgo_;
    }
    /**
     * <code>optional bool use_mem_size_first_algo = 1 [default = true];</code>
     */
    public Builder setUseMemSizeFirstAlgo(boolean value) {
      bitField0_ |= 0x00000001;
      useMemSizeFirstAlgo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool use_mem_size_first_algo = 1 [default = true];</code>
     */
    public Builder clearUseMemSizeFirstAlgo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      useMemSizeFirstAlgo_ = true;
      onChanged();
      return this;
    }

    private boolean useMutualExclusionFirstAlgo_ = true;
    /**
     * <code>optional bool use_mutual_exclusion_first_algo = 2 [default = true];</code>
     */
    public boolean hasUseMutualExclusionFirstAlgo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool use_mutual_exclusion_first_algo = 2 [default = true];</code>
     */
    public boolean getUseMutualExclusionFirstAlgo() {
      return useMutualExclusionFirstAlgo_;
    }
    /**
     * <code>optional bool use_mutual_exclusion_first_algo = 2 [default = true];</code>
     */
    public Builder setUseMutualExclusionFirstAlgo(boolean value) {
      bitField0_ |= 0x00000002;
      useMutualExclusionFirstAlgo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool use_mutual_exclusion_first_algo = 2 [default = true];</code>
     */
    public Builder clearUseMutualExclusionFirstAlgo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      useMutualExclusionFirstAlgo_ = true;
      onChanged();
      return this;
    }

    private boolean useTimeLineAlgo_ ;
    /**
     * <code>optional bool use_time_line_algo = 3 [default = false];</code>
     */
    public boolean hasUseTimeLineAlgo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool use_time_line_algo = 3 [default = false];</code>
     */
    public boolean getUseTimeLineAlgo() {
      return useTimeLineAlgo_;
    }
    /**
     * <code>optional bool use_time_line_algo = 3 [default = false];</code>
     */
    public Builder setUseTimeLineAlgo(boolean value) {
      bitField0_ |= 0x00000004;
      useTimeLineAlgo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool use_time_line_algo = 3 [default = false];</code>
     */
    public Builder clearUseTimeLineAlgo() {
      bitField0_ = (bitField0_ & ~0x00000004);
      useTimeLineAlgo_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:oneflow.MemoryAllocationAlgorithmConf)
  }

  // @@protoc_insertion_point(class_scope:oneflow.MemoryAllocationAlgorithmConf)
  private static final org.oneflow.core.job.MemoryAllocationAlgorithmConf DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.oneflow.core.job.MemoryAllocationAlgorithmConf();
  }

  public static org.oneflow.core.job.MemoryAllocationAlgorithmConf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<MemoryAllocationAlgorithmConf>
      PARSER = new com.google.protobuf.AbstractParser<MemoryAllocationAlgorithmConf>() {
    public MemoryAllocationAlgorithmConf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MemoryAllocationAlgorithmConf(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MemoryAllocationAlgorithmConf> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MemoryAllocationAlgorithmConf> getParserForType() {
    return PARSER;
  }

  public org.oneflow.core.job.MemoryAllocationAlgorithmConf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

