// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/job/sbp_parallel.proto

package org.oneflow.core.job;

/**
 * Protobuf type {@code oneflow.ParallelDistribution}
 */
public  final class ParallelDistribution extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:oneflow.ParallelDistribution)
    ParallelDistributionOrBuilder {
  // Use ParallelDistribution.newBuilder() to construct.
  private ParallelDistribution(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ParallelDistribution() {
    sbpParallel_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ParallelDistribution(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              sbpParallel_ = new java.util.ArrayList<org.oneflow.core.job.SbpParallel>();
              mutable_bitField0_ |= 0x00000001;
            }
            sbpParallel_.add(
                input.readMessage(org.oneflow.core.job.SbpParallel.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        sbpParallel_ = java.util.Collections.unmodifiableList(sbpParallel_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.oneflow.core.job.SbpParallelOuterClass.internal_static_oneflow_ParallelDistribution_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.oneflow.core.job.SbpParallelOuterClass.internal_static_oneflow_ParallelDistribution_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.oneflow.core.job.ParallelDistribution.class, org.oneflow.core.job.ParallelDistribution.Builder.class);
  }

  public static final int SBP_PARALLEL_FIELD_NUMBER = 1;
  private java.util.List<org.oneflow.core.job.SbpParallel> sbpParallel_;
  /**
   * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
   */
  public java.util.List<org.oneflow.core.job.SbpParallel> getSbpParallelList() {
    return sbpParallel_;
  }
  /**
   * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
   */
  public java.util.List<? extends org.oneflow.core.job.SbpParallelOrBuilder> 
      getSbpParallelOrBuilderList() {
    return sbpParallel_;
  }
  /**
   * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
   */
  public int getSbpParallelCount() {
    return sbpParallel_.size();
  }
  /**
   * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
   */
  public org.oneflow.core.job.SbpParallel getSbpParallel(int index) {
    return sbpParallel_.get(index);
  }
  /**
   * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
   */
  public org.oneflow.core.job.SbpParallelOrBuilder getSbpParallelOrBuilder(
      int index) {
    return sbpParallel_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getSbpParallelCount(); i++) {
      if (!getSbpParallel(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < sbpParallel_.size(); i++) {
      output.writeMessage(1, sbpParallel_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < sbpParallel_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, sbpParallel_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.oneflow.core.job.ParallelDistribution)) {
      return super.equals(obj);
    }
    org.oneflow.core.job.ParallelDistribution other = (org.oneflow.core.job.ParallelDistribution) obj;

    boolean result = true;
    result = result && getSbpParallelList()
        .equals(other.getSbpParallelList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getSbpParallelCount() > 0) {
      hash = (37 * hash) + SBP_PARALLEL_FIELD_NUMBER;
      hash = (53 * hash) + getSbpParallelList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.oneflow.core.job.ParallelDistribution parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.job.ParallelDistribution parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.job.ParallelDistribution parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.job.ParallelDistribution parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.job.ParallelDistribution parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.ParallelDistribution parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.job.ParallelDistribution parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.ParallelDistribution parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.job.ParallelDistribution parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.ParallelDistribution parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.oneflow.core.job.ParallelDistribution prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code oneflow.ParallelDistribution}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:oneflow.ParallelDistribution)
      org.oneflow.core.job.ParallelDistributionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.oneflow.core.job.SbpParallelOuterClass.internal_static_oneflow_ParallelDistribution_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.oneflow.core.job.SbpParallelOuterClass.internal_static_oneflow_ParallelDistribution_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.oneflow.core.job.ParallelDistribution.class, org.oneflow.core.job.ParallelDistribution.Builder.class);
    }

    // Construct using org.oneflow.core.job.ParallelDistribution.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSbpParallelFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (sbpParallelBuilder_ == null) {
        sbpParallel_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        sbpParallelBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.oneflow.core.job.SbpParallelOuterClass.internal_static_oneflow_ParallelDistribution_descriptor;
    }

    public org.oneflow.core.job.ParallelDistribution getDefaultInstanceForType() {
      return org.oneflow.core.job.ParallelDistribution.getDefaultInstance();
    }

    public org.oneflow.core.job.ParallelDistribution build() {
      org.oneflow.core.job.ParallelDistribution result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.oneflow.core.job.ParallelDistribution buildPartial() {
      org.oneflow.core.job.ParallelDistribution result = new org.oneflow.core.job.ParallelDistribution(this);
      int from_bitField0_ = bitField0_;
      if (sbpParallelBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          sbpParallel_ = java.util.Collections.unmodifiableList(sbpParallel_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.sbpParallel_ = sbpParallel_;
      } else {
        result.sbpParallel_ = sbpParallelBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.oneflow.core.job.ParallelDistribution) {
        return mergeFrom((org.oneflow.core.job.ParallelDistribution)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.oneflow.core.job.ParallelDistribution other) {
      if (other == org.oneflow.core.job.ParallelDistribution.getDefaultInstance()) return this;
      if (sbpParallelBuilder_ == null) {
        if (!other.sbpParallel_.isEmpty()) {
          if (sbpParallel_.isEmpty()) {
            sbpParallel_ = other.sbpParallel_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSbpParallelIsMutable();
            sbpParallel_.addAll(other.sbpParallel_);
          }
          onChanged();
        }
      } else {
        if (!other.sbpParallel_.isEmpty()) {
          if (sbpParallelBuilder_.isEmpty()) {
            sbpParallelBuilder_.dispose();
            sbpParallelBuilder_ = null;
            sbpParallel_ = other.sbpParallel_;
            bitField0_ = (bitField0_ & ~0x00000001);
            sbpParallelBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSbpParallelFieldBuilder() : null;
          } else {
            sbpParallelBuilder_.addAllMessages(other.sbpParallel_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      for (int i = 0; i < getSbpParallelCount(); i++) {
        if (!getSbpParallel(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.oneflow.core.job.ParallelDistribution parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.oneflow.core.job.ParallelDistribution) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<org.oneflow.core.job.SbpParallel> sbpParallel_ =
      java.util.Collections.emptyList();
    private void ensureSbpParallelIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        sbpParallel_ = new java.util.ArrayList<org.oneflow.core.job.SbpParallel>(sbpParallel_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.oneflow.core.job.SbpParallel, org.oneflow.core.job.SbpParallel.Builder, org.oneflow.core.job.SbpParallelOrBuilder> sbpParallelBuilder_;

    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public java.util.List<org.oneflow.core.job.SbpParallel> getSbpParallelList() {
      if (sbpParallelBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sbpParallel_);
      } else {
        return sbpParallelBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public int getSbpParallelCount() {
      if (sbpParallelBuilder_ == null) {
        return sbpParallel_.size();
      } else {
        return sbpParallelBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public org.oneflow.core.job.SbpParallel getSbpParallel(int index) {
      if (sbpParallelBuilder_ == null) {
        return sbpParallel_.get(index);
      } else {
        return sbpParallelBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public Builder setSbpParallel(
        int index, org.oneflow.core.job.SbpParallel value) {
      if (sbpParallelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSbpParallelIsMutable();
        sbpParallel_.set(index, value);
        onChanged();
      } else {
        sbpParallelBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public Builder setSbpParallel(
        int index, org.oneflow.core.job.SbpParallel.Builder builderForValue) {
      if (sbpParallelBuilder_ == null) {
        ensureSbpParallelIsMutable();
        sbpParallel_.set(index, builderForValue.build());
        onChanged();
      } else {
        sbpParallelBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public Builder addSbpParallel(org.oneflow.core.job.SbpParallel value) {
      if (sbpParallelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSbpParallelIsMutable();
        sbpParallel_.add(value);
        onChanged();
      } else {
        sbpParallelBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public Builder addSbpParallel(
        int index, org.oneflow.core.job.SbpParallel value) {
      if (sbpParallelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSbpParallelIsMutable();
        sbpParallel_.add(index, value);
        onChanged();
      } else {
        sbpParallelBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public Builder addSbpParallel(
        org.oneflow.core.job.SbpParallel.Builder builderForValue) {
      if (sbpParallelBuilder_ == null) {
        ensureSbpParallelIsMutable();
        sbpParallel_.add(builderForValue.build());
        onChanged();
      } else {
        sbpParallelBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public Builder addSbpParallel(
        int index, org.oneflow.core.job.SbpParallel.Builder builderForValue) {
      if (sbpParallelBuilder_ == null) {
        ensureSbpParallelIsMutable();
        sbpParallel_.add(index, builderForValue.build());
        onChanged();
      } else {
        sbpParallelBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public Builder addAllSbpParallel(
        java.lang.Iterable<? extends org.oneflow.core.job.SbpParallel> values) {
      if (sbpParallelBuilder_ == null) {
        ensureSbpParallelIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sbpParallel_);
        onChanged();
      } else {
        sbpParallelBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public Builder clearSbpParallel() {
      if (sbpParallelBuilder_ == null) {
        sbpParallel_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        sbpParallelBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public Builder removeSbpParallel(int index) {
      if (sbpParallelBuilder_ == null) {
        ensureSbpParallelIsMutable();
        sbpParallel_.remove(index);
        onChanged();
      } else {
        sbpParallelBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public org.oneflow.core.job.SbpParallel.Builder getSbpParallelBuilder(
        int index) {
      return getSbpParallelFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public org.oneflow.core.job.SbpParallelOrBuilder getSbpParallelOrBuilder(
        int index) {
      if (sbpParallelBuilder_ == null) {
        return sbpParallel_.get(index);  } else {
        return sbpParallelBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public java.util.List<? extends org.oneflow.core.job.SbpParallelOrBuilder> 
         getSbpParallelOrBuilderList() {
      if (sbpParallelBuilder_ != null) {
        return sbpParallelBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sbpParallel_);
      }
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public org.oneflow.core.job.SbpParallel.Builder addSbpParallelBuilder() {
      return getSbpParallelFieldBuilder().addBuilder(
          org.oneflow.core.job.SbpParallel.getDefaultInstance());
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public org.oneflow.core.job.SbpParallel.Builder addSbpParallelBuilder(
        int index) {
      return getSbpParallelFieldBuilder().addBuilder(
          index, org.oneflow.core.job.SbpParallel.getDefaultInstance());
    }
    /**
     * <code>repeated .oneflow.SbpParallel sbp_parallel = 1;</code>
     */
    public java.util.List<org.oneflow.core.job.SbpParallel.Builder> 
         getSbpParallelBuilderList() {
      return getSbpParallelFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.oneflow.core.job.SbpParallel, org.oneflow.core.job.SbpParallel.Builder, org.oneflow.core.job.SbpParallelOrBuilder> 
        getSbpParallelFieldBuilder() {
      if (sbpParallelBuilder_ == null) {
        sbpParallelBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.oneflow.core.job.SbpParallel, org.oneflow.core.job.SbpParallel.Builder, org.oneflow.core.job.SbpParallelOrBuilder>(
                sbpParallel_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        sbpParallel_ = null;
      }
      return sbpParallelBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:oneflow.ParallelDistribution)
  }

  // @@protoc_insertion_point(class_scope:oneflow.ParallelDistribution)
  private static final org.oneflow.core.job.ParallelDistribution DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.oneflow.core.job.ParallelDistribution();
  }

  public static org.oneflow.core.job.ParallelDistribution getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ParallelDistribution>
      PARSER = new com.google.protobuf.AbstractParser<ParallelDistribution>() {
    public ParallelDistribution parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ParallelDistribution(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ParallelDistribution> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParallelDistribution> getParserForType() {
    return PARSER;
  }

  public org.oneflow.core.job.ParallelDistribution getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

