// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/job/job_conf.proto

package org.oneflow.core.job;

/**
 * Protobuf type {@code oneflow.WeightDecayConf}
 */
public  final class WeightDecayConf extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:oneflow.WeightDecayConf)
    WeightDecayConfOrBuilder {
  // Use WeightDecayConf.newBuilder() to construct.
  private WeightDecayConf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeightDecayConf() {
    weightDecayRate_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WeightDecayConf(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 13: {
            bitField0_ |= 0x00000001;
            weightDecayRate_ = input.readFloat();
            break;
          }
          case 18: {
            org.oneflow.core.job.WeightDecayFilterPatternSet.Builder subBuilder = null;
            if (weightDecayFilterTypeCase_ == 2) {
              subBuilder = ((org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_).toBuilder();
            }
            weightDecayFilterType_ =
                input.readMessage(org.oneflow.core.job.WeightDecayFilterPatternSet.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_);
              weightDecayFilterType_ = subBuilder.buildPartial();
            }
            weightDecayFilterTypeCase_ = 2;
            break;
          }
          case 26: {
            org.oneflow.core.job.WeightDecayFilterPatternSet.Builder subBuilder = null;
            if (weightDecayFilterTypeCase_ == 3) {
              subBuilder = ((org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_).toBuilder();
            }
            weightDecayFilterType_ =
                input.readMessage(org.oneflow.core.job.WeightDecayFilterPatternSet.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_);
              weightDecayFilterType_ = subBuilder.buildPartial();
            }
            weightDecayFilterTypeCase_ = 3;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.oneflow.core.job.JobConf.internal_static_oneflow_WeightDecayConf_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.oneflow.core.job.JobConf.internal_static_oneflow_WeightDecayConf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.oneflow.core.job.WeightDecayConf.class, org.oneflow.core.job.WeightDecayConf.Builder.class);
  }

  private int bitField0_;
  private int weightDecayFilterTypeCase_ = 0;
  private java.lang.Object weightDecayFilterType_;
  public enum WeightDecayFilterTypeCase
      implements com.google.protobuf.Internal.EnumLite {
    INCLUDES(2),
    EXCLUDES(3),
    WEIGHTDECAYFILTERTYPE_NOT_SET(0);
    private final int value;
    private WeightDecayFilterTypeCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static WeightDecayFilterTypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static WeightDecayFilterTypeCase forNumber(int value) {
      switch (value) {
        case 2: return INCLUDES;
        case 3: return EXCLUDES;
        case 0: return WEIGHTDECAYFILTERTYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public WeightDecayFilterTypeCase
  getWeightDecayFilterTypeCase() {
    return WeightDecayFilterTypeCase.forNumber(
        weightDecayFilterTypeCase_);
  }

  public static final int WEIGHT_DECAY_RATE_FIELD_NUMBER = 1;
  private float weightDecayRate_;
  /**
   * <code>required float weight_decay_rate = 1;</code>
   */
  public boolean hasWeightDecayRate() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required float weight_decay_rate = 1;</code>
   */
  public float getWeightDecayRate() {
    return weightDecayRate_;
  }

  public static final int INCLUDES_FIELD_NUMBER = 2;
  /**
   * <code>optional .oneflow.WeightDecayFilterPatternSet includes = 2;</code>
   */
  public boolean hasIncludes() {
    return weightDecayFilterTypeCase_ == 2;
  }
  /**
   * <code>optional .oneflow.WeightDecayFilterPatternSet includes = 2;</code>
   */
  public org.oneflow.core.job.WeightDecayFilterPatternSet getIncludes() {
    if (weightDecayFilterTypeCase_ == 2) {
       return (org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_;
    }
    return org.oneflow.core.job.WeightDecayFilterPatternSet.getDefaultInstance();
  }
  /**
   * <code>optional .oneflow.WeightDecayFilterPatternSet includes = 2;</code>
   */
  public org.oneflow.core.job.WeightDecayFilterPatternSetOrBuilder getIncludesOrBuilder() {
    if (weightDecayFilterTypeCase_ == 2) {
       return (org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_;
    }
    return org.oneflow.core.job.WeightDecayFilterPatternSet.getDefaultInstance();
  }

  public static final int EXCLUDES_FIELD_NUMBER = 3;
  /**
   * <code>optional .oneflow.WeightDecayFilterPatternSet excludes = 3;</code>
   */
  public boolean hasExcludes() {
    return weightDecayFilterTypeCase_ == 3;
  }
  /**
   * <code>optional .oneflow.WeightDecayFilterPatternSet excludes = 3;</code>
   */
  public org.oneflow.core.job.WeightDecayFilterPatternSet getExcludes() {
    if (weightDecayFilterTypeCase_ == 3) {
       return (org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_;
    }
    return org.oneflow.core.job.WeightDecayFilterPatternSet.getDefaultInstance();
  }
  /**
   * <code>optional .oneflow.WeightDecayFilterPatternSet excludes = 3;</code>
   */
  public org.oneflow.core.job.WeightDecayFilterPatternSetOrBuilder getExcludesOrBuilder() {
    if (weightDecayFilterTypeCase_ == 3) {
       return (org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_;
    }
    return org.oneflow.core.job.WeightDecayFilterPatternSet.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasWeightDecayRate()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeFloat(1, weightDecayRate_);
    }
    if (weightDecayFilterTypeCase_ == 2) {
      output.writeMessage(2, (org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_);
    }
    if (weightDecayFilterTypeCase_ == 3) {
      output.writeMessage(3, (org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, weightDecayRate_);
    }
    if (weightDecayFilterTypeCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_);
    }
    if (weightDecayFilterTypeCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.oneflow.core.job.WeightDecayConf)) {
      return super.equals(obj);
    }
    org.oneflow.core.job.WeightDecayConf other = (org.oneflow.core.job.WeightDecayConf) obj;

    boolean result = true;
    result = result && (hasWeightDecayRate() == other.hasWeightDecayRate());
    if (hasWeightDecayRate()) {
      result = result && (
          java.lang.Float.floatToIntBits(getWeightDecayRate())
          == java.lang.Float.floatToIntBits(
              other.getWeightDecayRate()));
    }
    result = result && getWeightDecayFilterTypeCase().equals(
        other.getWeightDecayFilterTypeCase());
    if (!result) return false;
    switch (weightDecayFilterTypeCase_) {
      case 2:
        result = result && getIncludes()
            .equals(other.getIncludes());
        break;
      case 3:
        result = result && getExcludes()
            .equals(other.getExcludes());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasWeightDecayRate()) {
      hash = (37 * hash) + WEIGHT_DECAY_RATE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getWeightDecayRate());
    }
    switch (weightDecayFilterTypeCase_) {
      case 2:
        hash = (37 * hash) + INCLUDES_FIELD_NUMBER;
        hash = (53 * hash) + getIncludes().hashCode();
        break;
      case 3:
        hash = (37 * hash) + EXCLUDES_FIELD_NUMBER;
        hash = (53 * hash) + getExcludes().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.oneflow.core.job.WeightDecayConf parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.job.WeightDecayConf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.job.WeightDecayConf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.oneflow.core.job.WeightDecayConf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.oneflow.core.job.WeightDecayConf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.WeightDecayConf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.job.WeightDecayConf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.WeightDecayConf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.oneflow.core.job.WeightDecayConf parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.oneflow.core.job.WeightDecayConf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.oneflow.core.job.WeightDecayConf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code oneflow.WeightDecayConf}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:oneflow.WeightDecayConf)
      org.oneflow.core.job.WeightDecayConfOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.oneflow.core.job.JobConf.internal_static_oneflow_WeightDecayConf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.oneflow.core.job.JobConf.internal_static_oneflow_WeightDecayConf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.oneflow.core.job.WeightDecayConf.class, org.oneflow.core.job.WeightDecayConf.Builder.class);
    }

    // Construct using org.oneflow.core.job.WeightDecayConf.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      weightDecayRate_ = 0F;
      bitField0_ = (bitField0_ & ~0x00000001);
      weightDecayFilterTypeCase_ = 0;
      weightDecayFilterType_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.oneflow.core.job.JobConf.internal_static_oneflow_WeightDecayConf_descriptor;
    }

    public org.oneflow.core.job.WeightDecayConf getDefaultInstanceForType() {
      return org.oneflow.core.job.WeightDecayConf.getDefaultInstance();
    }

    public org.oneflow.core.job.WeightDecayConf build() {
      org.oneflow.core.job.WeightDecayConf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.oneflow.core.job.WeightDecayConf buildPartial() {
      org.oneflow.core.job.WeightDecayConf result = new org.oneflow.core.job.WeightDecayConf(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.weightDecayRate_ = weightDecayRate_;
      if (weightDecayFilterTypeCase_ == 2) {
        if (includesBuilder_ == null) {
          result.weightDecayFilterType_ = weightDecayFilterType_;
        } else {
          result.weightDecayFilterType_ = includesBuilder_.build();
        }
      }
      if (weightDecayFilterTypeCase_ == 3) {
        if (excludesBuilder_ == null) {
          result.weightDecayFilterType_ = weightDecayFilterType_;
        } else {
          result.weightDecayFilterType_ = excludesBuilder_.build();
        }
      }
      result.bitField0_ = to_bitField0_;
      result.weightDecayFilterTypeCase_ = weightDecayFilterTypeCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.oneflow.core.job.WeightDecayConf) {
        return mergeFrom((org.oneflow.core.job.WeightDecayConf)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.oneflow.core.job.WeightDecayConf other) {
      if (other == org.oneflow.core.job.WeightDecayConf.getDefaultInstance()) return this;
      if (other.hasWeightDecayRate()) {
        setWeightDecayRate(other.getWeightDecayRate());
      }
      switch (other.getWeightDecayFilterTypeCase()) {
        case INCLUDES: {
          mergeIncludes(other.getIncludes());
          break;
        }
        case EXCLUDES: {
          mergeExcludes(other.getExcludes());
          break;
        }
        case WEIGHTDECAYFILTERTYPE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasWeightDecayRate()) {
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.oneflow.core.job.WeightDecayConf parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.oneflow.core.job.WeightDecayConf) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int weightDecayFilterTypeCase_ = 0;
    private java.lang.Object weightDecayFilterType_;
    public WeightDecayFilterTypeCase
        getWeightDecayFilterTypeCase() {
      return WeightDecayFilterTypeCase.forNumber(
          weightDecayFilterTypeCase_);
    }

    public Builder clearWeightDecayFilterType() {
      weightDecayFilterTypeCase_ = 0;
      weightDecayFilterType_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private float weightDecayRate_ ;
    /**
     * <code>required float weight_decay_rate = 1;</code>
     */
    public boolean hasWeightDecayRate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float weight_decay_rate = 1;</code>
     */
    public float getWeightDecayRate() {
      return weightDecayRate_;
    }
    /**
     * <code>required float weight_decay_rate = 1;</code>
     */
    public Builder setWeightDecayRate(float value) {
      bitField0_ |= 0x00000001;
      weightDecayRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required float weight_decay_rate = 1;</code>
     */
    public Builder clearWeightDecayRate() {
      bitField0_ = (bitField0_ & ~0x00000001);
      weightDecayRate_ = 0F;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.oneflow.core.job.WeightDecayFilterPatternSet, org.oneflow.core.job.WeightDecayFilterPatternSet.Builder, org.oneflow.core.job.WeightDecayFilterPatternSetOrBuilder> includesBuilder_;
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet includes = 2;</code>
     */
    public boolean hasIncludes() {
      return weightDecayFilterTypeCase_ == 2;
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet includes = 2;</code>
     */
    public org.oneflow.core.job.WeightDecayFilterPatternSet getIncludes() {
      if (includesBuilder_ == null) {
        if (weightDecayFilterTypeCase_ == 2) {
          return (org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_;
        }
        return org.oneflow.core.job.WeightDecayFilterPatternSet.getDefaultInstance();
      } else {
        if (weightDecayFilterTypeCase_ == 2) {
          return includesBuilder_.getMessage();
        }
        return org.oneflow.core.job.WeightDecayFilterPatternSet.getDefaultInstance();
      }
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet includes = 2;</code>
     */
    public Builder setIncludes(org.oneflow.core.job.WeightDecayFilterPatternSet value) {
      if (includesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        weightDecayFilterType_ = value;
        onChanged();
      } else {
        includesBuilder_.setMessage(value);
      }
      weightDecayFilterTypeCase_ = 2;
      return this;
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet includes = 2;</code>
     */
    public Builder setIncludes(
        org.oneflow.core.job.WeightDecayFilterPatternSet.Builder builderForValue) {
      if (includesBuilder_ == null) {
        weightDecayFilterType_ = builderForValue.build();
        onChanged();
      } else {
        includesBuilder_.setMessage(builderForValue.build());
      }
      weightDecayFilterTypeCase_ = 2;
      return this;
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet includes = 2;</code>
     */
    public Builder mergeIncludes(org.oneflow.core.job.WeightDecayFilterPatternSet value) {
      if (includesBuilder_ == null) {
        if (weightDecayFilterTypeCase_ == 2 &&
            weightDecayFilterType_ != org.oneflow.core.job.WeightDecayFilterPatternSet.getDefaultInstance()) {
          weightDecayFilterType_ = org.oneflow.core.job.WeightDecayFilterPatternSet.newBuilder((org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_)
              .mergeFrom(value).buildPartial();
        } else {
          weightDecayFilterType_ = value;
        }
        onChanged();
      } else {
        if (weightDecayFilterTypeCase_ == 2) {
          includesBuilder_.mergeFrom(value);
        }
        includesBuilder_.setMessage(value);
      }
      weightDecayFilterTypeCase_ = 2;
      return this;
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet includes = 2;</code>
     */
    public Builder clearIncludes() {
      if (includesBuilder_ == null) {
        if (weightDecayFilterTypeCase_ == 2) {
          weightDecayFilterTypeCase_ = 0;
          weightDecayFilterType_ = null;
          onChanged();
        }
      } else {
        if (weightDecayFilterTypeCase_ == 2) {
          weightDecayFilterTypeCase_ = 0;
          weightDecayFilterType_ = null;
        }
        includesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet includes = 2;</code>
     */
    public org.oneflow.core.job.WeightDecayFilterPatternSet.Builder getIncludesBuilder() {
      return getIncludesFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet includes = 2;</code>
     */
    public org.oneflow.core.job.WeightDecayFilterPatternSetOrBuilder getIncludesOrBuilder() {
      if ((weightDecayFilterTypeCase_ == 2) && (includesBuilder_ != null)) {
        return includesBuilder_.getMessageOrBuilder();
      } else {
        if (weightDecayFilterTypeCase_ == 2) {
          return (org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_;
        }
        return org.oneflow.core.job.WeightDecayFilterPatternSet.getDefaultInstance();
      }
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet includes = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.oneflow.core.job.WeightDecayFilterPatternSet, org.oneflow.core.job.WeightDecayFilterPatternSet.Builder, org.oneflow.core.job.WeightDecayFilterPatternSetOrBuilder> 
        getIncludesFieldBuilder() {
      if (includesBuilder_ == null) {
        if (!(weightDecayFilterTypeCase_ == 2)) {
          weightDecayFilterType_ = org.oneflow.core.job.WeightDecayFilterPatternSet.getDefaultInstance();
        }
        includesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.oneflow.core.job.WeightDecayFilterPatternSet, org.oneflow.core.job.WeightDecayFilterPatternSet.Builder, org.oneflow.core.job.WeightDecayFilterPatternSetOrBuilder>(
                (org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_,
                getParentForChildren(),
                isClean());
        weightDecayFilterType_ = null;
      }
      weightDecayFilterTypeCase_ = 2;
      onChanged();;
      return includesBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.oneflow.core.job.WeightDecayFilterPatternSet, org.oneflow.core.job.WeightDecayFilterPatternSet.Builder, org.oneflow.core.job.WeightDecayFilterPatternSetOrBuilder> excludesBuilder_;
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet excludes = 3;</code>
     */
    public boolean hasExcludes() {
      return weightDecayFilterTypeCase_ == 3;
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet excludes = 3;</code>
     */
    public org.oneflow.core.job.WeightDecayFilterPatternSet getExcludes() {
      if (excludesBuilder_ == null) {
        if (weightDecayFilterTypeCase_ == 3) {
          return (org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_;
        }
        return org.oneflow.core.job.WeightDecayFilterPatternSet.getDefaultInstance();
      } else {
        if (weightDecayFilterTypeCase_ == 3) {
          return excludesBuilder_.getMessage();
        }
        return org.oneflow.core.job.WeightDecayFilterPatternSet.getDefaultInstance();
      }
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet excludes = 3;</code>
     */
    public Builder setExcludes(org.oneflow.core.job.WeightDecayFilterPatternSet value) {
      if (excludesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        weightDecayFilterType_ = value;
        onChanged();
      } else {
        excludesBuilder_.setMessage(value);
      }
      weightDecayFilterTypeCase_ = 3;
      return this;
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet excludes = 3;</code>
     */
    public Builder setExcludes(
        org.oneflow.core.job.WeightDecayFilterPatternSet.Builder builderForValue) {
      if (excludesBuilder_ == null) {
        weightDecayFilterType_ = builderForValue.build();
        onChanged();
      } else {
        excludesBuilder_.setMessage(builderForValue.build());
      }
      weightDecayFilterTypeCase_ = 3;
      return this;
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet excludes = 3;</code>
     */
    public Builder mergeExcludes(org.oneflow.core.job.WeightDecayFilterPatternSet value) {
      if (excludesBuilder_ == null) {
        if (weightDecayFilterTypeCase_ == 3 &&
            weightDecayFilterType_ != org.oneflow.core.job.WeightDecayFilterPatternSet.getDefaultInstance()) {
          weightDecayFilterType_ = org.oneflow.core.job.WeightDecayFilterPatternSet.newBuilder((org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_)
              .mergeFrom(value).buildPartial();
        } else {
          weightDecayFilterType_ = value;
        }
        onChanged();
      } else {
        if (weightDecayFilterTypeCase_ == 3) {
          excludesBuilder_.mergeFrom(value);
        }
        excludesBuilder_.setMessage(value);
      }
      weightDecayFilterTypeCase_ = 3;
      return this;
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet excludes = 3;</code>
     */
    public Builder clearExcludes() {
      if (excludesBuilder_ == null) {
        if (weightDecayFilterTypeCase_ == 3) {
          weightDecayFilterTypeCase_ = 0;
          weightDecayFilterType_ = null;
          onChanged();
        }
      } else {
        if (weightDecayFilterTypeCase_ == 3) {
          weightDecayFilterTypeCase_ = 0;
          weightDecayFilterType_ = null;
        }
        excludesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet excludes = 3;</code>
     */
    public org.oneflow.core.job.WeightDecayFilterPatternSet.Builder getExcludesBuilder() {
      return getExcludesFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet excludes = 3;</code>
     */
    public org.oneflow.core.job.WeightDecayFilterPatternSetOrBuilder getExcludesOrBuilder() {
      if ((weightDecayFilterTypeCase_ == 3) && (excludesBuilder_ != null)) {
        return excludesBuilder_.getMessageOrBuilder();
      } else {
        if (weightDecayFilterTypeCase_ == 3) {
          return (org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_;
        }
        return org.oneflow.core.job.WeightDecayFilterPatternSet.getDefaultInstance();
      }
    }
    /**
     * <code>optional .oneflow.WeightDecayFilterPatternSet excludes = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.oneflow.core.job.WeightDecayFilterPatternSet, org.oneflow.core.job.WeightDecayFilterPatternSet.Builder, org.oneflow.core.job.WeightDecayFilterPatternSetOrBuilder> 
        getExcludesFieldBuilder() {
      if (excludesBuilder_ == null) {
        if (!(weightDecayFilterTypeCase_ == 3)) {
          weightDecayFilterType_ = org.oneflow.core.job.WeightDecayFilterPatternSet.getDefaultInstance();
        }
        excludesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.oneflow.core.job.WeightDecayFilterPatternSet, org.oneflow.core.job.WeightDecayFilterPatternSet.Builder, org.oneflow.core.job.WeightDecayFilterPatternSetOrBuilder>(
                (org.oneflow.core.job.WeightDecayFilterPatternSet) weightDecayFilterType_,
                getParentForChildren(),
                isClean());
        weightDecayFilterType_ = null;
      }
      weightDecayFilterTypeCase_ = 3;
      onChanged();;
      return excludesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:oneflow.WeightDecayConf)
  }

  // @@protoc_insertion_point(class_scope:oneflow.WeightDecayConf)
  private static final org.oneflow.core.job.WeightDecayConf DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.oneflow.core.job.WeightDecayConf();
  }

  public static org.oneflow.core.job.WeightDecayConf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<WeightDecayConf>
      PARSER = new com.google.protobuf.AbstractParser<WeightDecayConf>() {
    public WeightDecayConf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new WeightDecayConf(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WeightDecayConf> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeightDecayConf> getParserForType() {
    return PARSER;
  }

  public org.oneflow.core.job.WeightDecayConf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

