// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/control/control.proto

package org.oneflow.core.control;

public interface ClearResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.ClearResponse)
    com.google.protobuf.MessageOrBuilder {
}
