// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/graph/boxing/collective_boxing.proto

package org.oneflow.core.graph.boxing;

public interface OpDescOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.boxing.collective.OpDesc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required .oneflow.boxing.collective.OpType op_type = 2;</code>
   */
  boolean hasOpType();
  /**
   * <code>required .oneflow.boxing.collective.OpType op_type = 2;</code>
   */
  org.oneflow.core.graph.boxing.OpType getOpType();

  /**
   * <code>optional .oneflow.boxing.collective.ReduceMethod reduce_method = 3;</code>
   */
  boolean hasReduceMethod();
  /**
   * <code>optional .oneflow.boxing.collective.ReduceMethod reduce_method = 3;</code>
   */
  org.oneflow.core.graph.boxing.ReduceMethod getReduceMethod();

  /**
   * <code>optional int64 root = 4;</code>
   */
  boolean hasRoot();
  /**
   * <code>optional int64 root = 4;</code>
   */
  long getRoot();

  /**
   * <code>required .oneflow.DataType data_type = 5;</code>
   */
  boolean hasDataType();
  /**
   * <code>required .oneflow.DataType data_type = 5;</code>
   */
  org.oneflow.core.common.DataType getDataType();

  /**
   * <code>required .oneflow.ShapeProto shape = 6;</code>
   */
  boolean hasShape();
  /**
   * <code>required .oneflow.ShapeProto shape = 6;</code>
   */
  org.oneflow.core.common.ShapeProto getShape();
  /**
   * <code>required .oneflow.ShapeProto shape = 6;</code>
   */
  org.oneflow.core.common.ShapeProtoOrBuilder getShapeOrBuilder();

  /**
   * <code>required int64 num_ranks = 7;</code>
   */
  boolean hasNumRanks();
  /**
   * <code>required int64 num_ranks = 7;</code>
   */
  long getNumRanks();

  /**
   * <code>required .oneflow.boxing.collective.Backend backend = 8;</code>
   */
  boolean hasBackend();
  /**
   * <code>required .oneflow.boxing.collective.Backend backend = 8;</code>
   */
  org.oneflow.core.graph.boxing.Backend getBackend();
}
