// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oneflow/core/graph/boxing/collective_boxing.proto

package org.oneflow.core.graph.boxing;

public interface RequestSetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneflow.boxing.collective.RequestSet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .oneflow.boxing.collective.RequestDesc request = 1;</code>
   */
  java.util.List<org.oneflow.core.graph.boxing.RequestDesc> 
      getRequestList();
  /**
   * <code>repeated .oneflow.boxing.collective.RequestDesc request = 1;</code>
   */
  org.oneflow.core.graph.boxing.RequestDesc getRequest(int index);
  /**
   * <code>repeated .oneflow.boxing.collective.RequestDesc request = 1;</code>
   */
  int getRequestCount();
  /**
   * <code>repeated .oneflow.boxing.collective.RequestDesc request = 1;</code>
   */
  java.util.List<? extends org.oneflow.core.graph.boxing.RequestDescOrBuilder> 
      getRequestOrBuilderList();
  /**
   * <code>repeated .oneflow.boxing.collective.RequestDesc request = 1;</code>
   */
  org.oneflow.core.graph.boxing.RequestDescOrBuilder getRequestOrBuilder(
      int index);
}
